/*
 * Generated by Agent 5: Formal Artifact Generation Agent
 * Artifact: candidate CBMC harness
 * Target function: mlk_poly_add
 * Harness function: harness_mlk_poly_add
 *
 * SCIENTIFIC GUARDRAIL:
 * This file is a candidate formal-verification artifact only.
 * It does not prove ML-KEM and it must be reviewed by the Critic Agent,
 * checked by CBMC, and inspected by the human researcher.
 *
 * Human-learned template:
 * This mlk_poly_add harness shape was derived from the corrected Run 002
 * experiment. It snapshots old r, applies the documented no-overflow
 * precondition, calls mlk_poly_add(&r, &b), and checks the coefficient-wise
 * in-place update property.
 *
 * Generation note: Configured for CBMC harness generation. Agent 2 v2 FIPS-aware outputs were available and used for grounding where safe. Agent 4 v2 traceability outputs were available and recorded.
 * Selected candidate property types: array_bounds, input_pointer_validity, loop_bound, memory_safety, output_pointer_validity, parameter_consistency, spec_code_alignment
 *
 * Recommended CBMC command saved in 04_artifact_manifest.json:
 * cbmc /home/girish/thesis-agent-workflow/runs/run_003_mlk_poly_add_agent_improved_cbmc/04_generated_harness.c /home/girish/thesis-agent-workflow/inputs/code/poly.c -I /home/girish/thesis-agent-workflow/inputs/code --function harness_mlk_poly_add --bounds-check --pointer-check --signed-overflow-check --unsigned-overflow-check --unwind 257 --unwinding-assertions
 */

#include <assert.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "poly.h"
#include "params.h"
#include "cbmc.h"
#include "common.h"
#include <limits.h>

#ifndef __CPROVER__
#define __CPROVER_assume(cond) ((void)0)
#endif

/* Target signature observed by Code Understanding Agent: MLK_INTERNAL_API void mlk_poly_add(mlk_poly *r, const mlk_poly *b) */
/* Nondeterministic input functions for CBMC. */
extern int16_t nondet_int16_t(void);

void harness_mlk_poly_add(void)
{
  mlk_poly r;
  mlk_poly b;
  int16_t old_r_coeffs[MLKEM_N];

  /* Initialize both in-place input r and input b, then snapshot old r. */
  for (unsigned int i = 0; i < MLKEM_N; i++)
  {
    r.coeffs[i] = nondet_int16_t();
    b.coeffs[i] = nondet_int16_t();

    /* Documented precondition from poly.h: coefficient addition must not overflow int16_t. */
    __CPROVER_assume((int32_t)r.coeffs[i] + (int32_t)b.coeffs[i] <= INT16_MAX);
    __CPROVER_assume((int32_t)r.coeffs[i] + (int32_t)b.coeffs[i] >= INT16_MIN);

    old_r_coeffs[i] = r.coeffs[i];
  }

  mlk_poly_add(&r, &b);

  /* Check selected local in-place coefficient-wise update property. */
  for (unsigned int i = 0; i < MLKEM_N; i++)
  {
    assert(r.coeffs[i] ==
           (int16_t)((int32_t)old_r_coeffs[i] + (int32_t)b.coeffs[i]));
  }
}
