#!/usr/bin/env python3
"""
Agent 6: Review / Critic Agent v2
=================================

Purpose
-------
This agent reviews the candidate formal-verification artifact generated by Agent 5.
For the current thesis prototype, the artifact is usually a CBMC C harness:

  04_generated_harness.c

This v2 upgrade preserves the old pipeline contract while adding stronger
FIPS-aware/spec-grounding checks.

Legacy inputs
-------------
- 04_generated_harness.c, or artifact passed through --artifact
- 04_artifact_manifest.json
- 01_spec_summary.json
- 02_code_summary.json
- 03_candidate_properties.json
- config JSON

New optional inputs from Agent 2 v2 / Agent 4 v2 / Agent 5 v2
-------------------------------------------------------------
- selected_spec_excerpt.txt
- 01_algorithm_blocks.json
- 01_symbol_table.json
- 01_parameter_table.json
- 01_equations_constraints.json
- 01_preconditions_postconditions.json
- 01_spec_to_code_hints.json
- 03_spec_code_traceability.json
- 03_agent2v2_integration_report.json
- 03_property_evidence_matrix.csv
- 04_spec_grounding_report.json
- 04_spec_grounded_assertion_plan.json
- 04_harness_assumption_traceability.csv

Legacy outputs preserved
------------------------
- 05_critic_review.json
- 05_critic_review.md
- llm_prompts/05_critic_review_prompt.txt
- agent_status/05_critic_review_status.json

New optional outputs
--------------------
- 05_spec_grounding_review.json
- 05_assumption_evidence_review.csv
- 05_assertion_algorithm_alignment.csv
- 05_symbol_uncertainty_review.json

Scientific guardrail
--------------------
This agent DOES NOT prove the artifact correct. It is a deterministic reviewer that catches
obvious and common artifact problems before CBMC/formal-tool execution. CBMC and human
review remain the authority.
"""

from __future__ import annotations

import argparse
import csv
import datetime as _dt
import hashlib
import json
import os
import re
import sys
import traceback
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple


AGENT_NAME = "review_critic_agent"
SCHEMA_VERSION = "2.0"
DEFAULT_ARTIFACT = "04_generated_harness.c"


# ---------------------------------------------------------------------------
# Basic IO helpers
# ---------------------------------------------------------------------------

def utc_now() -> str:
    return _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds")


def read_json(path: Path, default: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    if not path.exists():
        if default is not None:
            return default
        raise FileNotFoundError(f"Required JSON file not found: {path}")
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        if default is not None:
            return default
        raise ValueError(f"Expected JSON object in {path}, got {type(data).__name__}")
    return data


def read_json_any(path: Path, default: Any = None) -> Any:
    if default is None:
        default = {}
    if not path.exists():
        return default
    try:
        return json.loads(path.read_text(encoding="utf-8", errors="replace"))
    except Exception:
        return default


def write_json(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")
    tmp.replace(path)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def append_jsonl(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(data, ensure_ascii=False) + "\n")


def read_text_if_exists(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except FileNotFoundError:
        return ""


def sha256_short(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", errors="replace")).hexdigest()[:16]


def as_list(value: Any) -> List[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def normalize_space(text: Any) -> str:
    return re.sub(r"\s+", " ", str(text or "")).strip()


def strip_c_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text or "", flags=re.S)
    text = re.sub(r"//.*?$", "", text, flags=re.M)
    return text


def find_project_root(config_path: Path) -> Path:
    parent = config_path.resolve().parent
    if parent.name == "configs":
        return parent.parent
    return parent


def resolve_path(project_root: Path, maybe_path: Optional[str], fallback: Optional[Path] = None) -> Path:
    if maybe_path:
        p = Path(maybe_path).expanduser()
        if not p.is_absolute():
            p = project_root / p
        return p.resolve()
    if fallback is None:
        raise ValueError("Missing required path and no fallback provided")
    return fallback.resolve()


def flatten_text(value: Any) -> str:
    if isinstance(value, str):
        return value
    try:
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    except Exception:
        return str(value)


def token_set(text: str) -> set[str]:
    return {t.lower() for t in re.findall(r"[A-Za-z_][A-Za-z0-9_]*|\d+", text or "")}


def safe_csv_value(value: Any) -> str:
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False)
    return "" if value is None else str(value)


def write_csv(path: Path, rows: List[Dict[str, Any]], fieldnames: Optional[List[str]] = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if fieldnames is None:
        fieldnames = []
        for row in rows:
            for key in row:
                if key not in fieldnames:
                    fieldnames.append(key)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: safe_csv_value(row.get(key, "")) for key in fieldnames})


def read_csv_rows(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


# ---------------------------------------------------------------------------
# C/harness extraction helpers
# ---------------------------------------------------------------------------

def indexed_lines(text: str) -> List[Tuple[int, str]]:
    return list(enumerate((text or "").splitlines(), start=1))


def evidence_for_line(path: Path, line_no: int, line: str) -> Dict[str, Any]:
    return {
        "source_file": str(path),
        "start_line": line_no,
        "end_line": line_no,
        "text": line.strip(),
    }


def find_lines_matching(text: str, pattern: str, flags: int = 0) -> List[Tuple[int, str, re.Match[str]]]:
    out: List[Tuple[int, str, re.Match[str]]] = []
    rx = re.compile(pattern, flags)
    for line_no, line in indexed_lines(text):
        m = rx.search(line)
        if m:
            out.append((line_no, line, m))
    return out


def classify_assumption(expr: str) -> str:
    e = expr.replace(" ", "").lower()
    if e in {"0", "false", "(0)", "(false)"}:
        return "contradictory_or_vacuous"
    if e in {"1", "true", "(1)", "(true)"}:
        return "trivial"
    if re.search(r"coeffs\s*\[.*?\]\s*(<=|<|>=|>)\s*-?\d+", expr):
        return "coefficient_numeric_bound"
    if re.search(r"\w+\s*!=\s*null|\w+\s*!=\s*0", expr, re.I):
        return "pointer_non_null"
    if re.search(r"\w+\s*<\s*\w+|\w+\s*<=\s*\w+", expr):
        return "relational_bound"
    return "general_assumption"


def classify_assertion(expr: str) -> str:
    e = expr.replace(" ", "").lower()
    if e in {"1", "true", "(1)", "(true)"}:
        return "trivial"
    if e in {"0", "false", "(0)", "(false)"}:
        return "always_fails"
    if "==" in expr and "coeffs" in expr:
        return "coefficient_functional_equality"
    if "<" in expr or ">" in expr:
        return "range_or_bounds_assertion"
    return "general_assertion"


def extract_assumptions(text: str, path: Path) -> List[Dict[str, Any]]:
    assumptions: List[Dict[str, Any]] = []
    for line_no, line, m in find_lines_matching(text, r"__CPROVER_assume\s*\((.*)\)\s*;"):
        expr = normalize_space(m.group(1))
        assumptions.append({
            "expression": expr,
            "line": line_no,
            "evidence": evidence_for_line(path, line_no, line),
            "classification": classify_assumption(expr),
        })
    return assumptions


def extract_assertions(text: str, path: Path) -> List[Dict[str, Any]]:
    assertions: List[Dict[str, Any]] = []
    for line_no, line, m in find_lines_matching(text, r"\bassert\s*\((.*)\)\s*;"):
        expr = normalize_space(m.group(1))
        assertions.append({
            "expression": expr,
            "line": line_no,
            "evidence": evidence_for_line(path, line_no, line),
            "classification": classify_assertion(expr),
        })
    return assertions


def extract_includes(text: str, path: Path) -> List[Dict[str, Any]]:
    includes: List[Dict[str, Any]] = []
    for line_no, line, m in find_lines_matching(text, r"^\s*#\s*include\s*([<\"].*[>\"])"):
        includes.append({"include": m.group(1), "line": line_no, "evidence": evidence_for_line(path, line_no, line)})
    return includes


def extract_loops(text: str, path: Path) -> List[Dict[str, Any]]:
    loops: List[Dict[str, Any]] = []
    for line_no, line, m in find_lines_matching(text, r"\bfor\s*\((.*?)\)"):
        raw = normalize_space(m.group(1))
        parts = [p.strip() for p in raw.split(";")]
        loops.append({
            "kind": "for",
            "raw": raw,
            "init": parts[0] if len(parts) > 0 else "",
            "condition": parts[1] if len(parts) > 1 else "",
            "increment": parts[2] if len(parts) > 2 else "",
            "line": line_no,
            "evidence": evidence_for_line(path, line_no, line),
        })
    for line_no, line, m in find_lines_matching(text, r"\bwhile\s*\((.*?)\)"):
        loops.append({
            "kind": "while",
            "raw": normalize_space(m.group(1)),
            "condition": normalize_space(m.group(1)),
            "line": line_no,
            "evidence": evidence_for_line(path, line_no, line),
        })
    return loops


def extract_array_accesses(text: str, path: Path) -> List[Dict[str, Any]]:
    accesses: List[Dict[str, Any]] = []
    for line_no, line in indexed_lines(strip_c_comments(text)):
        for m in re.finditer(r"([A-Za-z_]\w*(?:->|\.)?[A-Za-z_]\w*)\s*\[\s*([^\]]+)\s*\]", line):
            accesses.append({
                "access": f"{m.group(1)}[{m.group(2).strip()}]",
                "base": m.group(1),
                "index": m.group(2).strip(),
                "line": line_no,
                "evidence": evidence_for_line(path, line_no, line),
            })
    return accesses


def extract_nondet_uses(text: str, path: Path) -> List[Dict[str, Any]]:
    uses: List[Dict[str, Any]] = []
    for line_no, line, m in find_lines_matching(text, r"\b(nondet_[A-Za-z0-9_]+)\s*\("):
        uses.append({"function": m.group(1), "line": line_no, "evidence": evidence_for_line(path, line_no, line)})
    return uses


def extract_function_calls(text: str) -> List[Dict[str, Any]]:
    clean = strip_c_comments(text)
    calls: List[Dict[str, Any]] = []
    keywords = {
        "if", "for", "while", "switch", "return", "sizeof", "assert", "__CPROVER_assume",
        "void", "int", "uint16_t", "int16_t", "uint32_t", "int32_t", "uint64_t", "int64_t",
    }
    for line_no, line in indexed_lines(clean):
        for m in re.finditer(r"\b([A-Za-z_]\w*)\s*\(", line):
            name = m.group(1)
            if name in keywords or name.startswith("nondet_"):
                continue
            if re.search(rf"\b{name}\s*\([^;]*\)\s*\{{", line):
                continue
            calls.append({"name": name, "line": line_no, "text": normalize_space(line)})
    return calls


def harness_declares_function(text: str, harness_function: str) -> bool:
    if not harness_function:
        return False
    return re.search(rf"\bvoid\s+{re.escape(harness_function)}\s*\(", text or "") is not None


def target_call_present(text: str, target_function: str) -> List[Dict[str, Any]]:
    if not target_function:
        return []
    calls: List[Dict[str, Any]] = []
    rx = re.compile(rf"\b{re.escape(target_function)}\s*\(")
    for line_no, line in indexed_lines(strip_c_comments(text)):
        if rx.search(line):
            # Avoid counting declarations/definitions where possible.
            if re.search(rf"^\s*(extern\s+)?[A-Za-z_][A-Za-z0-9_\s\*]*\b{re.escape(target_function)}\s*\(", line) and line.strip().endswith(";"):
                continue
            calls.append({"line": line_no, "evidence": evidence_for_line(Path("artifact"), line_no, line)})
    return calls


# ---------------------------------------------------------------------------
# Previous-output helpers
# ---------------------------------------------------------------------------

def get_target_function(config: Dict[str, Any], code_summary: Dict[str, Any], manifest: Dict[str, Any]) -> str:
    function = code_summary.get("function") if isinstance(code_summary.get("function"), dict) else {}
    return str(
        manifest.get("target_function")
        or function.get("detected_name")
        or code_summary.get("target_function_detected")
        or code_summary.get("target_function_requested")
        or config.get("target_function")
        or ""
    ).strip()


def get_harness_function(config: Dict[str, Any], manifest: Dict[str, Any], target_function: str) -> str:
    return str(
        manifest.get("harness_function")
        or config.get("harness_function")
        or (f"harness_{target_function}" if target_function else "")
    ).strip()


def get_spec_constants(spec_summary: Dict[str, Any], rich: Dict[str, Any]) -> Dict[str, Any]:
    constants = spec_summary.get("constants", {})
    out: Dict[str, Any] = dict(constants) if isinstance(constants, dict) else {}

    # Merge Agent 2 v2 parameter table/symbol info conservatively.
    param_table = rich.get("parameter_table")
    if isinstance(param_table, dict):
        for bucket in ("parameters", "constants", "rows"):
            for item in as_list(param_table.get(bucket)):
                if isinstance(item, dict):
                    name = item.get("name") or item.get("symbol") or item.get("parameter")
                    value = item.get("value")
                    if name and value is not None and str(name) not in out:
                        out[str(name)] = {"value": value, "source": "01_parameter_table.json"}

    symbol_table = rich.get("symbol_table")
    if isinstance(symbol_table, dict):
        for item in as_list(symbol_table.get("symbols")) + as_list(symbol_table.get("entries")):
            if isinstance(item, dict):
                name = item.get("symbol") or item.get("name")
                value = item.get("value")
                if name and value is not None and str(name) not in out:
                    out[str(name)] = {"value": value, "source": "01_symbol_table.json"}

    return out


def constant_value(constants: Dict[str, Any], name: str) -> Optional[Any]:
    aliases = {
        "N": ["N", "n", "KYBER_N", "MLKEM_N", "MLK_N"],
        "q": ["q", "Q", "KYBER_Q", "MLKEM_Q", "MLK_Q"],
    }.get(name, [name])
    for alias in aliases:
        item = constants.get(alias)
        if isinstance(item, dict):
            return item.get("value")
        if item is not None:
            return item
    return None


def selected_properties(properties: Dict[str, Any], manifest: Dict[str, Any]) -> List[Dict[str, Any]]:
    selected = (
        manifest.get("selected_properties_used")
        or manifest.get("selected_properties")
        or properties.get("first_harness_selection")
        or properties.get("selected_first_harness_properties")
    )
    if isinstance(selected, list) and selected:
        return [p for p in selected if isinstance(p, dict)]
    candidates = properties.get("candidate_properties")
    if isinstance(candidates, list):
        return [p for p in candidates if isinstance(p, dict)]
    return []


def issue(
    severity: str,
    issue_type: str,
    message: str,
    recommendation: str,
    evidence: Optional[Dict[str, Any]] = None,
    related_property_ids: Optional[List[str]] = None,
) -> Dict[str, Any]:
    data: Dict[str, Any] = {
        "severity": severity,
        "type": issue_type,
        "message": message,
        "recommendation": recommendation,
    }
    if evidence:
        data["evidence"] = evidence
    if related_property_ids:
        data["related_property_ids"] = related_property_ids
    return data


def highest_severity(issues: List[Dict[str, Any]]) -> str:
    rank = {"info": 0, "low": 1, "medium": 2, "high": 3, "critical": 4}
    if not issues:
        return "none"
    return max((str(i.get("severity", "info")).lower() for i in issues), key=lambda s: rank.get(s, 0))


def review_status_from_issues(issues: List[Dict[str, Any]], artifact_exists: bool) -> str:
    if not artifact_exists:
        return "reject"
    severities = [str(i.get("severity", "info")).lower() for i in issues]
    if "critical" in severities or "high" in severities:
        return "needs_revision"
    if "medium" in severities:
        return "conditional_accept_for_tool"
    return "accept_for_tool"


def score_from_issues(issues: List[Dict[str, Any]]) -> Dict[str, Any]:
    weights = {"critical": 40, "high": 25, "medium": 10, "low": 3, "info": 1}
    raw = sum(weights.get(str(i.get("severity", "info")).lower(), 1) for i in issues)
    risk = min(100, raw)
    quality = max(0, 100 - risk)
    return {
        "risk_score_0_to_100": risk,
        "quality_score_0_to_100": quality,
        "highest_severity": highest_severity(issues),
        "issue_count": len(issues),
        "severity_counts": {
            sev: sum(1 for i in issues if str(i.get("severity", "")).lower() == sev)
            for sev in ["critical", "high", "medium", "low", "info"]
        },
    }


# ---------------------------------------------------------------------------
# Agent 2/4/5 v2 rich-context loading and analysis
# ---------------------------------------------------------------------------

def load_rich_context(run_dir: Path) -> Dict[str, Any]:
    return {
        "selected_spec_excerpt": read_text_if_exists(run_dir / "selected_spec_excerpt.txt"),
        "algorithm_blocks": read_json_any(run_dir / "01_algorithm_blocks.json", {}),
        "symbol_table": read_json_any(run_dir / "01_symbol_table.json", {}),
        "parameter_table": read_json_any(run_dir / "01_parameter_table.json", {}),
        "equations_constraints": read_json_any(run_dir / "01_equations_constraints.json", {}),
        "preconditions_postconditions": read_json_any(run_dir / "01_preconditions_postconditions.json", {}),
        "spec_to_code_hints": read_json_any(run_dir / "01_spec_to_code_hints.json", {}),
        "spec_code_traceability": read_json_any(run_dir / "03_spec_code_traceability.json", {}),
        "agent2v2_integration_report": read_json_any(run_dir / "03_agent2v2_integration_report.json", {}),
        "property_evidence_matrix_rows": read_csv_rows(run_dir / "03_property_evidence_matrix.csv"),
        "spec_grounding_report": read_json_any(run_dir / "04_spec_grounding_report.json", {}),
        "spec_grounded_assertion_plan": read_json_any(run_dir / "04_spec_grounded_assertion_plan.json", {}),
        "harness_assumption_traceability_rows": read_csv_rows(run_dir / "04_harness_assumption_traceability.csv"),
    }


def collect_algorithm_texts(rich: Dict[str, Any]) -> List[Dict[str, Any]]:
    data = rich.get("algorithm_blocks")
    blocks: List[Any] = []
    if isinstance(data, dict):
        for key in ("algorithm_blocks", "algorithms", "blocks", "items"):
            blocks.extend(as_list(data.get(key)))
    elif isinstance(data, list):
        blocks = data

    out: List[Dict[str, Any]] = []
    for i, block in enumerate(blocks, start=1):
        if isinstance(block, dict):
            text = normalize_space(
                block.get("text")
                or block.get("body")
                or block.get("algorithm_text")
                or block.get("raw")
                or flatten_text(block)
            )
            name = str(block.get("name") or block.get("algorithm_name") or f"algorithm_{i}")
            evidence = block.get("evidence") or {
                "source_file": "01_algorithm_blocks.json",
                "start_line": block.get("start_line"),
                "end_line": block.get("end_line"),
            }
        else:
            text = normalize_space(block)
            name = f"algorithm_{i}"
            evidence = {"source_file": "01_algorithm_blocks.json"}
        if text:
            out.append({"name": name, "text": text, "evidence": evidence})
    return out


def collect_algorithm_assignments(rich: Dict[str, Any]) -> List[Dict[str, Any]]:
    assignments: List[Dict[str, Any]] = []
    for block in collect_algorithm_texts(rich):
        text = block["text"]
        # Accept ASCII =, <-, ←, := as assignment-like.
        for m in re.finditer(r"([A-Za-z_][A-Za-z0-9_\.\-\>\[\]]+)\s*(?:<-|←|:=|=)\s*([^;\n]+)", text):
            assignments.append({
                "lhs": normalize_space(m.group(1)),
                "rhs": normalize_space(m.group(2)),
                "algorithm": block["name"],
                "evidence": block["evidence"],
                "raw": normalize_space(m.group(0)),
            })

    # Some Agent 2 v2 schemas store steps explicitly.
    data = rich.get("algorithm_blocks")
    candidates: List[Any] = []
    if isinstance(data, dict):
        for key in ("algorithm_blocks", "algorithms", "blocks", "items"):
            for block in as_list(data.get(key)):
                if isinstance(block, dict):
                    candidates.extend(as_list(block.get("steps")))
                    candidates.extend(as_list(block.get("operations")))
                    candidates.extend(as_list(block.get("assignments")))
    for item in candidates:
        if isinstance(item, dict):
            lhs = item.get("lhs") or item.get("left")
            rhs = item.get("rhs") or item.get("right") or item.get("expression")
            if lhs and rhs:
                assignments.append({
                    "lhs": normalize_space(lhs),
                    "rhs": normalize_space(rhs),
                    "algorithm": str(item.get("algorithm") or item.get("algorithm_name") or "unknown_algorithm"),
                    "evidence": item.get("evidence") or {"source_file": "01_algorithm_blocks.json"},
                    "raw": normalize_space(flatten_text(item)),
                })
    return assignments


def collect_prepost_texts(rich: Dict[str, Any]) -> List[Dict[str, Any]]:
    data = rich.get("preconditions_postconditions")
    out: List[Dict[str, Any]] = []
    if isinstance(data, dict):
        for bucket in ("preconditions", "postconditions", "input_requirements", "output_guarantees", "items"):
            for item in as_list(data.get(bucket)):
                text = normalize_space(flatten_text(item if isinstance(item, str) else item.get("text") or item.get("description") or item))
                if text:
                    out.append({"kind": bucket, "text": text, "evidence": item.get("evidence") if isinstance(item, dict) else {"source_file": "01_preconditions_postconditions.json"}})
    elif isinstance(data, list):
        for item in data:
            text = normalize_space(flatten_text(item))
            if text:
                out.append({"kind": "item", "text": text, "evidence": {"source_file": "01_preconditions_postconditions.json"}})
    return out


def collect_constraints_texts(rich: Dict[str, Any]) -> List[Dict[str, Any]]:
    data = rich.get("equations_constraints")
    out: List[Dict[str, Any]] = []
    if isinstance(data, dict):
        for bucket in ("equations", "constraints", "ranges", "relations", "items"):
            for item in as_list(data.get(bucket)):
                text = normalize_space(flatten_text(item if isinstance(item, str) else item.get("text") or item.get("expression") or item))
                if text:
                    out.append({"kind": bucket, "text": text, "evidence": item.get("evidence") if isinstance(item, dict) else {"source_file": "01_equations_constraints.json"}})
    elif isinstance(data, list):
        for item in data:
            text = normalize_space(flatten_text(item))
            if text:
                out.append({"kind": "item", "text": text, "evidence": {"source_file": "01_equations_constraints.json"}})
    return out


def rich_uncertainty_texts(spec_summary: Dict[str, Any], properties: Dict[str, Any], manifest: Dict[str, Any], rich: Dict[str, Any]) -> List[str]:
    texts: List[str] = []
    for source in (spec_summary, properties, manifest, rich.get("agent2v2_integration_report", {}), rich.get("spec_grounding_report", {})):
        if isinstance(source, dict):
            for key in ("uncertainties", "quality_flags", "warnings", "known_limitations", "human_review_flags"):
                for item in as_list(source.get(key)):
                    text = normalize_space(flatten_text(item))
                    if text:
                        texts.append(text)
    return list(dict.fromkeys(texts))


def assumption_has_traceability(assumption: Dict[str, Any], manifest: Dict[str, Any], rich: Dict[str, Any]) -> Tuple[bool, str]:
    expr = assumption.get("expression", "")
    expr_tokens = token_set(expr)
    if not expr_tokens:
        return False, "empty assumption expression"

    # Agent 5 v2 CSV traceability is strongest.
    for row in rich.get("harness_assumption_traceability_rows", []):
        row_text = flatten_text(row)
        if expr in row_text or len(expr_tokens & token_set(row_text)) >= max(2, min(4, len(expr_tokens))):
            return True, "matched 04_harness_assumption_traceability.csv"

    for item in as_list(manifest.get("candidate_assumptions_inserted")):
        text = flatten_text(item)
        if expr in text or len(expr_tokens & token_set(text)) >= max(2, min(4, len(expr_tokens))):
            return True, "matched 04_artifact_manifest.json candidate_assumptions_inserted"

    # Preconditions/constraints can support numeric bounds, but not automatically if vague.
    for item in collect_prepost_texts(rich) + collect_constraints_texts(rich):
        text = item["text"]
        if len(expr_tokens & token_set(text)) >= max(2, min(4, len(expr_tokens))):
            return True, f"matched {item['kind']} from rich spec context"

    return False, "no direct traceability evidence found"


def assertion_algorithm_alignment(assertion: Dict[str, Any], rich: Dict[str, Any], manifest: Dict[str, Any], properties: Dict[str, Any]) -> Dict[str, Any]:
    expr = assertion.get("expression", "")
    expr_norm = expr.replace("->", ".")
    expr_tokens = token_set(expr_norm)
    best = {
        "assertion": expr,
        "line": assertion.get("line"),
        "alignment_status": "not_checked",
        "best_algorithm": "",
        "best_algorithm_step": "",
        "score": 0.0,
        "evidence": {},
        "note": "",
    }

    assignments = collect_algorithm_assignments(rich)
    for assign in assignments:
        candidate_text = f"{assign.get('lhs')} {assign.get('rhs')} {assign.get('raw')}".replace("->", ".")
        cand_tokens = token_set(candidate_text)
        if not cand_tokens:
            continue
        overlap = len(expr_tokens & cand_tokens)
        denom = max(1, min(len(expr_tokens), len(cand_tokens)))
        score = overlap / denom
        if score > best["score"]:
            best.update({
                "alignment_status": "aligned_candidate" if score >= 0.35 else "weak_alignment",
                "best_algorithm": assign.get("algorithm", ""),
                "best_algorithm_step": assign.get("raw", ""),
                "score": round(score, 3),
                "evidence": assign.get("evidence") or {},
                "note": "Token overlap against parsed algorithm assignment.",
            })

    # Agent 5 v2 assertion plan can also support assertions.
    plan = rich.get("spec_grounded_assertion_plan")
    for item in as_list(plan.get("assertions") if isinstance(plan, dict) else []):
        text = flatten_text(item)
        score = len(expr_tokens & token_set(text)) / max(1, min(len(expr_tokens), len(token_set(text)) or 1))
        if score > best["score"]:
            best.update({
                "alignment_status": "aligned_candidate" if score >= 0.35 else "weak_alignment",
                "best_algorithm": "04_spec_grounded_assertion_plan",
                "best_algorithm_step": text[:300],
                "score": round(score, 3),
                "evidence": item.get("evidence") if isinstance(item, dict) else {"source_file": "04_spec_grounded_assertion_plan.json"},
                "note": "Matched Agent 5 v2 assertion plan.",
            })

    if not assignments and not plan:
        best["alignment_status"] = "no_algorithm_or_assertion_plan_available"
        best["note"] = "Agent 2/5 v2 rich algorithm/assertion-plan files were not available."
    elif best["score"] < 0.2:
        best["alignment_status"] = "not_aligned"
        best["note"] = "No strong match to parsed algorithm assignments or assertion plan."
    return best


def detect_symbol_misuse(artifact_text: str, constants: Dict[str, Any], rich: Dict[str, Any]) -> List[Dict[str, Any]]:
    findings: List[Dict[str, Any]] = []
    q_val = constant_value(constants, "q")
    n_val = constant_value(constants, "N")
    lower = artifact_text.lower()

    # q used as raw coefficient input bound is suspicious unless preconditions mention input coefficient ranges.
    if q_val is not None and str(q_val) in artifact_text and "__CPROVER_assume" in artifact_text:
        prepost_text = "\n".join(x["text"].lower() for x in collect_prepost_texts(rich) + collect_constraints_texts(rich))
        if not re.search(r"(input|coefficient|coeffs).{0,80}(range|bound|<|>|≤|≥|between)", prepost_text):
            findings.append({
                "severity": "medium",
                "type": "q_used_without_input_range_context",
                "message": f"The harness uses q={q_val} in/near assumptions, but parsed preconditions do not clearly justify q as an input coefficient bound.",
                "recommendation": "Use q as modulus context only unless the selected FIPS/spec section explicitly states the input coefficient range.",
            })

    if n_val is not None:
        uses_n = str(n_val) in artifact_text or re.search(r"\b(KYBER_N|MLKEM_N|MLK_N|N)\b", artifact_text)
        if not uses_n and re.search(r"\bfor\s*\(", artifact_text):
            findings.append({
                "severity": "medium",
                "type": "n_not_used_for_loop_bound",
                "message": f"Spec/parameter table indicates N={n_val}, but harness loops do not visibly use N or a compatible implementation macro/literal.",
                "recommendation": "Use the implementation macro for polynomial size or document why another loop bound is correct.",
            })

    # Symbols that are common but absent from rich symbol table.
    symbol_table_text = flatten_text(rich.get("symbol_table", {})).lower()
    for sym in sorted(set(re.findall(r"\b(eta1|eta2|du|dv|k|q|n)\b", lower))):
        if sym not in symbol_table_text and sym not in {"q", "n"}:
            findings.append({
                "severity": "low",
                "type": "symbol_used_without_symbol_table_entry",
                "message": f"Symbol `{sym}` appears in the artifact but was not found in the parsed symbol table.",
                "recommendation": "Confirm whether the symbol comes from code macros, selected FIPS parameters, or an unsupported assumption.",
            })

    return findings


def check_uncertainty_handling(artifact_text: str, manifest: Dict[str, Any], rich: Dict[str, Any], uncertainties: List[str]) -> Dict[str, Any]:
    review_markers = ["human review", "candidate", "uncertain", "needs review", "critic"]
    combined = (artifact_text + "\n" + flatten_text(manifest)).lower()
    markers_present = [m for m in review_markers if m in combined]

    high_uncertainty_count = len(uncertainties)
    if high_uncertainty_count == 0:
        status = "no_uncertainties_recorded"
        severity = "info"
        message = "No upstream uncertainties were recorded."
    elif markers_present:
        status = "acknowledged"
        severity = "info"
        message = f"{high_uncertainty_count} uncertainty/limitation item(s) exist and artifact/manifest contains review markers."
    else:
        status = "ignored_or_not_visible"
        severity = "medium"
        message = f"{high_uncertainty_count} uncertainty/limitation item(s) exist, but the harness/manifest does not visibly acknowledge them."

    return {
        "status": status,
        "severity": severity,
        "message": message,
        "markers_present": markers_present,
        "uncertainty_count": high_uncertainty_count,
        "sample_uncertainties": uncertainties[:10],
    }


# ---------------------------------------------------------------------------
# Critic rules
# ---------------------------------------------------------------------------

def run_critic_rules(
    *,
    artifact_path: Path,
    artifact_text: str,
    config: Dict[str, Any],
    spec_summary: Dict[str, Any],
    code_summary: Dict[str, Any],
    properties: Dict[str, Any],
    manifest: Dict[str, Any],
    rich: Dict[str, Any],
    iteration: int,
) -> Dict[str, Any]:
    target_function = get_target_function(config, code_summary, manifest)
    harness_function = get_harness_function(config, manifest, target_function)
    selected = selected_properties(properties, manifest)
    selected_types = sorted({str(p.get("type", "unknown")) for p in selected})
    selected_ids = [str(p.get("id")) for p in selected if p.get("id")]

    artifact_exists = artifact_path.exists() and bool(artifact_text.strip())
    issues: List[Dict[str, Any]] = []
    positives: List[str] = []
    checklist: List[Dict[str, Any]] = []

    assumptions = extract_assumptions(artifact_text, artifact_path) if artifact_exists else []
    assertions = extract_assertions(artifact_text, artifact_path) if artifact_exists else []
    includes = extract_includes(artifact_text, artifact_path) if artifact_exists else []
    loops = extract_loops(artifact_text, artifact_path) if artifact_exists else []
    array_accesses = extract_array_accesses(artifact_text, artifact_path) if artifact_exists else []
    nondet_uses = extract_nondet_uses(artifact_text, artifact_path) if artifact_exists else []
    calls = extract_function_calls(artifact_text) if artifact_exists else []
    target_calls = target_call_present(artifact_text, target_function) if artifact_exists else []

    constants = get_spec_constants(spec_summary, rich)
    spec_n = constant_value(constants, "N")
    spec_q = constant_value(constants, "q")
    manifest_cmd = str(manifest.get("recommended_cbmc_command") or manifest.get("cbmc_command") or "")
    if not manifest_cmd:
        manifest_cmd = flatten_text(manifest.get("recommended_commands", ""))

    def add_check(name: str, passed: bool, details: str, severity_if_failed: str = "medium") -> None:
        checklist.append({"check": name, "passed": passed, "details": details, "severity_if_failed": severity_if_failed})

    if not artifact_exists:
        issues.append(issue(
            "critical",
            "missing_artifact",
            f"The expected artifact file was not found or is empty: {artifact_path}",
            "Re-run the Formal Artifact Generation Agent and confirm that 04_generated_harness.c is created.",
        ))
        add_check("artifact_exists", False, "Artifact file missing or empty", "critical")
        return {
            "target_function": target_function,
            "harness_function": harness_function,
            "selected_property_types": selected_types,
            "selected_property_ids": selected_ids,
            "assumptions": assumptions,
            "assertions": assertions,
            "includes": includes,
            "loops": loops,
            "array_accesses": array_accesses,
            "nondet_uses": nondet_uses,
            "function_calls": calls,
            "issues": issues,
            "positive_findings": positives,
            "checklist": checklist,
            "rich_reviews": {},
        }

    add_check("artifact_exists", True, f"Artifact found: {artifact_path}", "critical")
    positives.append("Artifact file exists and is non-empty.")

    lower_artifact = artifact_text.lower()
    has_candidate_guardrail = "candidate" in lower_artifact and ("does not prove" in lower_artifact or "must be reviewed" in lower_artifact or "human review" in lower_artifact)
    add_check("scientific_guardrail_comment", has_candidate_guardrail, "Harness states candidate/non-proof status" if has_candidate_guardrail else "Harness does not clearly state candidate/non-proof status", "low")
    if has_candidate_guardrail:
        positives.append("Artifact includes a candidate/non-proof guardrail comment.")
    else:
        issues.append(issue(
            "low",
            "missing_scientific_guardrail_comment",
            "The harness does not clearly state that it is only a candidate artifact and not a proof.",
            "Add a header comment saying the artifact must be reviewed by the Critic Agent, CBMC, and the human researcher.",
        ))

    has_harness = harness_declares_function(artifact_text, harness_function)
    add_check("harness_function_declared", has_harness, f"Expected harness function `{harness_function}` declared" if has_harness else f"Expected harness function `{harness_function}` not declared", "high")
    if has_harness:
        positives.append(f"Expected harness function `{harness_function}` is declared.")
    else:
        issues.append(issue(
            "high",
            "missing_harness_function",
            f"The artifact does not declare the expected harness function `{harness_function}`.",
            "Generate or rename the harness function so the CBMC command can target it with --function.",
        ))

    add_check("target_function_called", bool(target_calls), f"Target function `{target_function}` call found" if target_calls else f"No call to target function `{target_function}` found", "high")
    if target_calls:
        positives.append(f"Artifact calls the target function `{target_function}`.")
    else:
        issues.append(issue(
            "high",
            "missing_target_call",
            f"The harness does not call the selected target function `{target_function}`.",
            "Call the exact selected implementation function; otherwise CBMC may verify only harness scaffolding.",
        ))

    include_names = [x.get("include", "") for x in includes]
    has_assert_include = any("assert.h" in s for s in include_names)
    add_check("assert_header_included", has_assert_include, "assert.h included" if has_assert_include else "assert.h not included", "medium")
    if assertions and not has_assert_include:
        issues.append(issue(
            "medium",
            "missing_assert_header",
            "The harness uses assert(...) but does not visibly include <assert.h>.",
            "Include <assert.h> or ensure the build environment provides assert declarations safely.",
        ))
    elif has_assert_include:
        positives.append("Harness includes <assert.h> for C assertions.")

    # Assumption checks, now with richer v2 traceability.
    assumption_trace_rows: List[Dict[str, Any]] = []
    contradictory_assumptions = [a for a in assumptions if a.get("classification") == "contradictory_or_vacuous"]
    for a in assumptions:
        ok, source = assumption_has_traceability(a, manifest, rich)
        row = {
            "line": a.get("line"),
            "expression": a.get("expression"),
            "classification": a.get("classification"),
            "traceability_status": "supported_candidate" if ok else "not_traced",
            "traceability_source": source,
        }
        assumption_trace_rows.append(row)
        if not ok:
            sev = "high" if a.get("classification") in {"coefficient_numeric_bound", "relational_bound"} else "medium"
            issues.append(issue(
                sev,
                "assumption_without_traceability",
                f"The assumption `{a.get('expression')}` was not directly traced to Agent 2/4/5 evidence.",
                "Add evidence in Agent 5 manifest/traceability CSV, cite the selected spec precondition, or move this assumption to a human-reviewed variant.",
                a.get("evidence"),
            ))

    for a in contradictory_assumptions:
        issues.append(issue(
            "critical",
            "vacuous_assumption",
            f"The assumption `{a['expression']}` can make the proof vacuous or unreachable.",
            "Remove contradictory assumptions; every assumption should represent a real precondition.",
            a.get("evidence"),
        ))

    coefficient_bound_assumptions = [a for a in assumptions if a.get("classification") == "coefficient_numeric_bound"]
    prepost_constraint_text = "\n".join(x["text"].lower() for x in collect_prepost_texts(rich) + collect_constraints_texts(rich))
    has_explicit_bound_context = bool(re.search(r"(input|coefficient|coeffs).{0,120}(range|bound|<|>|≤|≥|between)", prepost_constraint_text))
    for a in coefficient_bound_assumptions:
        if not has_explicit_bound_context:
            issues.append(issue(
                "high",
                "unsupported_coefficient_bound_assumption",
                f"The coefficient bound assumption `{a['expression']}` is not clearly justified by parsed FIPS/spec preconditions.",
                "Either cite a precise input-bound rule from Agent 2 v2 outputs, or remove this automatic assumption.",
                a.get("evidence"),
            ))
    if coefficient_bound_assumptions and has_explicit_bound_context:
        positives.append("Coefficient numeric assumptions exist and parsed pre/post/constraint context appears to mention coefficient ranges.")
    elif not coefficient_bound_assumptions:
        positives.append("No unsupported default coefficient range assumptions were inserted by the harness.")

    add_check("no_contradictory_assumptions", not contradictory_assumptions, "No obviously contradictory assumptions found" if not contradictory_assumptions else "Contradictory/vacuous assumptions found", "critical")

    # Assertion checks, now with algorithm alignment.
    assertion_alignment_rows: List[Dict[str, Any]] = []
    if not assertions:
        has_builtin_checks = any(flag in manifest_cmd for flag in ["--bounds-check", "--pointer-check", "--signed-overflow-check"])
        severity = "medium" if not has_builtin_checks else "low"
        issues.append(issue(
            severity,
            "no_explicit_assertions",
            "The harness has no explicit assert(...) statements.",
            "This is acceptable only if selected properties are intentionally checked through CBMC built-in checks; document that clearly.",
        ))
    else:
        positives.append(f"Harness contains {len(assertions)} explicit assertion(s).")

    for a in assertions:
        cls = a.get("classification")
        if cls == "trivial":
            issues.append(issue(
                "high",
                "trivial_assertion",
                f"The assertion `{a['expression']}` is trivial and does not check selected implementation behavior.",
                "Replace trivial assertions with property-connected assertions or rely on CBMC built-in checks explicitly.",
                a.get("evidence"),
            ))
        elif cls == "always_fails":
            issues.append(issue(
                "high",
                "always_failing_assertion",
                f"The assertion `{a['expression']}` always fails and is likely a harness mistake.",
                "Replace it with a meaningful property assertion or remove it.",
                a.get("evidence"),
            ))

        alignment = assertion_algorithm_alignment(a, rich, manifest, properties)
        assertion_alignment_rows.append(alignment)
        if cls not in {"trivial", "always_fails"} and alignment["alignment_status"] in {"not_aligned", "weak_alignment"}:
            severity = "medium" if alignment["alignment_status"] == "not_aligned" else "low"
            issues.append(issue(
                severity,
                "assertion_not_aligned_with_parsed_algorithm",
                f"The assertion `{a.get('expression')}` does not strongly match parsed algorithm assignments or Agent 5 assertion plan.",
                "Check whether this assertion is implementation-derived only, or add explicit spec/algorithm evidence before relying on it.",
                a.get("evidence"),
            ))
        elif alignment["alignment_status"] == "aligned_candidate":
            positives.append(f"Assertion on line {a.get('line')} has candidate alignment to parsed algorithm/spec assertion plan.")

    functional_assertions = [a for a in assertions if a.get("classification") == "coefficient_functional_equality"]
    if functional_assertions:
        all_text = (flatten_text(code_summary) + "\n" + artifact_text).lower()
        if any(tok in all_text for tok in ["int16_t", "int8_t", "signed", "nondet_int16_t", "nondet_int8_t"]) and re.search(r"coeffs\s*\[.*?\].*\+.*coeffs\s*\[", all_text, re.S):
            issues.append(issue(
                "medium",
                "signed_overflow_risk_in_functional_assertion",
                "The coefficient equality assertion may involve signed small-integer addition, so CBMC may report signed overflow unless valid input bounds are justified.",
                "Separate memory-safety checking from arithmetic correctness, or add carefully justified coefficient preconditions before checking equality.",
                functional_assertions[0].get("evidence"),
                selected_ids,
            ))

    # CBMC command/check compatibility.
    recommended_flags = ["--bounds-check", "--pointer-check", "--unwinding-assertions"]
    missing_flags = [flag for flag in recommended_flags if flag not in manifest_cmd]
    if missing_flags:
        issues.append(issue(
            "medium",
            "missing_recommended_cbmc_flags",
            f"The recommended CBMC command/manifest does not visibly include: {', '.join(missing_flags)}.",
            "Add these checks unless the run intentionally excludes them and documents why.",
        ))
    else:
        positives.append("Recommended CBMC command includes bounds, pointer, and unwinding checks.")

    if loops:
        has_unwind = "--unwind" in manifest_cmd or any("unwind" in flatten_text(p).lower() for p in selected)
        add_check("loop_unwind_planned", has_unwind, "Loop unwind appears planned" if has_unwind else "Loop unwind not clearly planned", "medium")
        if not has_unwind:
            issues.append(issue(
                "medium",
                "missing_unwind_plan",
                "The harness contains loop(s), but no clear CBMC unwind plan was found.",
                "Use --unwind with --unwinding-assertions and document the selected bound.",
                loops[0].get("evidence"),
            ))
        else:
            positives.append("Loop unwinding is planned through CBMC command/properties.")

    input_params = as_list(code_summary.get("inputs"))
    if input_params and not nondet_uses:
        issues.append(issue(
            "medium",
            "missing_nondeterministic_inputs",
            "The selected function has likely input parameters, but the harness does not use visible nondeterministic input generation.",
            "Initialize relevant input fields with nondeterministic values so CBMC explores more than one fixed test case.",
        ))
    elif nondet_uses:
        positives.append(f"Harness uses nondeterministic input function(s): {', '.join(sorted({u['function'] for u in nondet_uses}))}.")

    selected_has_bounds = any(t in {"array_bounds", "memory_safety", "loop_bound", "algorithm_loop_bound"} for t in selected_types)
    if selected_has_bounds and not array_accesses and not loops:
        issues.append(issue(
            "medium",
            "safety_property_without_visible_accesses",
            "Safety/bounds properties are selected, but the harness has no visible array accesses or loops.",
            "Confirm the target call is enough for CBMC to check the implementation, and include source files in the CBMC command.",
        ))
    elif array_accesses:
        positives.append(f"Harness contains {len(array_accesses)} visible array access(es), useful for initialization/assertion review.")

    # FIPS symbol/constant checks.
    symbol_findings = detect_symbol_misuse(artifact_text, constants, rich)
    for finding in symbol_findings:
        issues.append(issue(finding["severity"], finding["type"], finding["message"], finding["recommendation"]))

    if spec_n is not None:
        uses_n_literal_or_symbol = str(spec_n) in artifact_text or re.search(r"\b(KYBER_N|MLKEM_N|MLK_N|N)\b", artifact_text)
        add_check("polynomial_size_constant_used", bool(uses_n_literal_or_symbol), f"Spec N={spec_n}; harness appears to use N/KYBER_N/literal" if uses_n_literal_or_symbol else f"Spec N={spec_n}; harness does not visibly use compatible size constant", "medium")
        if not uses_n_literal_or_symbol:
            issues.append(issue(
                "medium",
                "missing_polynomial_size_constant",
                f"The spec/parameter table contains N = {spec_n}, but the harness does not visibly use that bound or a known N macro.",
                "Use the implementation's verified polynomial-size macro or an explicitly justified constant.",
            ))
        else:
            positives.append(f"Harness appears to use a polynomial-size bound compatible with N={spec_n}.")

    # Uncertainty marker checks.
    uncertainties = rich_uncertainty_texts(spec_summary, properties, manifest, rich)
    uncertainty_review = check_uncertainty_handling(artifact_text, manifest, rich, uncertainties)
    if uncertainty_review["status"] == "ignored_or_not_visible":
        issues.append(issue(
            uncertainty_review["severity"],
            "upstream_uncertainties_not_acknowledged",
            uncertainty_review["message"],
            "Add human-review/uncertainty notes to the manifest or harness comments, and avoid strong claims based on uncertain extracted facts.",
        ))
    else:
        positives.append(uncertainty_review["message"])

    # Alias awareness.
    output_params = as_list(code_summary.get("outputs_or_inouts"))
    if output_params and len(input_params) >= 1:
        mentions_alias = any(word in lower_artifact for word in ["alias", "separation", "same object", "distinct"])
        if not mentions_alias:
            issues.append(issue(
                "low",
                "aliasing_not_discussed",
                "The function has pointer inputs/outputs, but the harness/review material does not discuss aliasing.",
                "Decide whether aliases like r == a or r == b are allowed by the implementation contract, and document the choice.",
            ))
        else:
            positives.append("Artifact text mentions aliasing/separation concerns.")

    # Property coverage.
    property_coverage: List[Dict[str, Any]] = []
    for p in selected:
        p_id = str(p.get("id", "unknown"))
        p_type = str(p.get("type", "unknown"))
        p_text = flatten_text(p).lower()
        covered_by: List[str] = []
        if p_type in {"array_bounds", "memory_safety", "pointer_validity", "input_pointer_validity", "output_pointer_validity", "algorithm_loop_bound"}:
            if any(flag in manifest_cmd for flag in ["--bounds-check", "--pointer-check"]):
                covered_by.append("cbmc_builtin_checks")
        if p_type in {"loop_bound", "array_bounds", "algorithm_loop_bound"} and "--unwind" in manifest_cmd:
            covered_by.append("unwind_plan")
        if "functional" in p_type or "equals" in p_text or "algorithm_functional_step" in p_type:
            if functional_assertions or any(r["alignment_status"] == "aligned_candidate" for r in assertion_alignment_rows):
                covered_by.append("explicit_or_spec_aligned_assertion")
        if p_type in {"parameter_consistency", "spec_code_alignment"}:
            if rich.get("spec_code_traceability") or rich.get("spec_grounding_report"):
                covered_by.append("traceability_report")
        property_coverage.append({
            "property_id": p_id,
            "property_type": p_type,
            "coverage_status": "covered_candidate" if covered_by else "not_clearly_covered",
            "covered_by": covered_by,
        })

    uncovered_high_priority = [
        c for c, p in zip(property_coverage, selected)
        if c["coverage_status"] == "not_clearly_covered" and str(p.get("priority", "")).lower() == "high"
    ]
    if uncovered_high_priority:
        issues.append(issue(
            "medium",
            "selected_property_not_clearly_covered",
            f"{len(uncovered_high_priority)} high-priority selected propertie(s) are not clearly covered by assertions, traceability, or CBMC flags.",
            "Either add explicit assertions/checks or update the property selection for this artifact.",
            related_property_ids=[str(c["property_id"]) for c in uncovered_high_priority],
        ))
    elif property_coverage:
        positives.append("Selected properties have at least candidate coverage through CBMC flags, explicit assertions, or traceability reports.")

    # Broad claim checks.
    for pat in [
        r"fully\s+prove[sd]?\s+ml-?kem",
        r"complete\s+proof\s+of\s+ml-?kem",
        r"formally\s+verified\s+entire",
        r"ai\s+proved",
    ]:
        for line_no, line, _ in find_lines_matching(artifact_text, pat, flags=re.I):
            issues.append(issue(
                "high",
                "unsafe_overclaim_in_artifact_text",
                "The artifact text appears to contain an unsafe proof overclaim.",
                "Rewrite it to say this is only a candidate artifact checked under selected assumptions.",
                evidence_for_line(artifact_path, line_no, line),
            ))

    # Deduplicate issues by type+message+line.
    seen = set()
    deduped: List[Dict[str, Any]] = []
    for it in issues:
        ev = it.get("evidence", {}) if isinstance(it.get("evidence"), dict) else {}
        key = (it.get("severity"), it.get("type"), it.get("message"), ev.get("start_line"))
        if key not in seen:
            seen.add(key)
            deduped.append(it)
    issues = deduped

    rich_reviews = {
        "assumption_evidence_review": assumption_trace_rows,
        "assertion_algorithm_alignment": assertion_alignment_rows,
        "symbol_misuse_findings": symbol_findings,
        "uncertainty_review": uncertainty_review,
        "rich_context_files_seen": {
            "algorithm_blocks": bool(rich.get("algorithm_blocks")),
            "symbol_table": bool(rich.get("symbol_table")),
            "parameter_table": bool(rich.get("parameter_table")),
            "equations_constraints": bool(rich.get("equations_constraints")),
            "preconditions_postconditions": bool(rich.get("preconditions_postconditions")),
            "spec_to_code_hints": bool(rich.get("spec_to_code_hints")),
            "spec_code_traceability": bool(rich.get("spec_code_traceability")),
            "spec_grounding_report": bool(rich.get("spec_grounding_report")),
            "spec_grounded_assertion_plan": bool(rich.get("spec_grounded_assertion_plan")),
            "harness_assumption_traceability_csv_rows": len(rich.get("harness_assumption_traceability_rows", [])),
        },
    }

    return {
        "target_function": target_function,
        "harness_function": harness_function,
        "selected_property_types": selected_types,
        "selected_property_ids": selected_ids,
        "assumptions": assumptions,
        "assertions": assertions,
        "includes": includes,
        "loops": loops,
        "array_accesses": array_accesses,
        "nondet_uses": nondet_uses,
        "function_calls": calls,
        "target_calls": target_calls,
        "property_coverage": property_coverage,
        "issues": issues,
        "positive_findings": positives,
        "checklist": checklist,
        "manifest_command_seen": manifest_cmd,
        "spec_constants_seen": {"N": spec_n, "q": spec_q},
        "iteration": iteration,
        "rich_reviews": rich_reviews,
    }


# ---------------------------------------------------------------------------
# Prompt and markdown rendering
# ---------------------------------------------------------------------------

def build_prompt_record(
    config: Dict[str, Any],
    spec_summary: Dict[str, Any],
    code_summary: Dict[str, Any],
    properties: Dict[str, Any],
    manifest: Dict[str, Any],
    rich: Dict[str, Any],
    artifact_text: str,
    artifact_path: Path,
) -> str:
    target = get_target_function(config, code_summary, manifest)
    harness = get_harness_function(config, manifest, target)
    selected = selected_properties(properties, manifest)
    selected_short = [
        {
            "id": p.get("id"),
            "type": p.get("type"),
            "priority": p.get("priority"),
            "description": p.get("description"),
        }
        for p in selected[:20]
    ]
    rich_summary = {
        "algorithm_blocks_available": bool(rich.get("algorithm_blocks")),
        "symbol_table_available": bool(rich.get("symbol_table")),
        "parameter_table_available": bool(rich.get("parameter_table")),
        "equations_constraints_available": bool(rich.get("equations_constraints")),
        "preconditions_postconditions_available": bool(rich.get("preconditions_postconditions")),
        "spec_grounding_report_available": bool(rich.get("spec_grounding_report")),
        "spec_grounded_assertion_plan_available": bool(rich.get("spec_grounded_assertion_plan")),
        "assumption_traceability_rows": len(rich.get("harness_assumption_traceability_rows", [])),
    }
    return f"""You are the Review / Critic Agent v2 for an AI-assisted formal-verification artifact workflow.

Task:
1. Review the generated CBMC harness.
2. Check whether assumptions are too strong or too weak.
3. Check whether assumptions have actual FIPS/spec evidence or Agent 5 traceability.
4. Check whether assertions match parsed algorithm assignments or assertion plans.
5. Check whether the harness misuses symbols/constants such as q and N.
6. Check whether uncertainty markers from previous agents were acknowledged.
7. Check whether the harness calls the correct target function.
8. Produce severity-labelled issues and recommended fixes.
9. Do not claim the artifact is a proof.

Target function: {target}
Harness function: {harness}
Artifact path: {artifact_path}

Selected properties summary:
{json.dumps(selected_short, indent=2, ensure_ascii=False)}

Rich v2 context:
{json.dumps(rich_summary, indent=2, ensure_ascii=False)}

Spec constants:
{json.dumps(get_spec_constants(spec_summary, rich), indent=2, ensure_ascii=False)[:4000]}

Code function summary:
{json.dumps(code_summary.get('function', {}), indent=2, ensure_ascii=False)[:4000]}

Artifact preview:
```c
{artifact_text[:8000]}
```

Return a structured JSON review. This file records the deterministic critic task even when no external LLM is used.
"""


def render_markdown(review: Dict[str, Any]) -> str:
    score = review.get("quality_metrics", {})
    rich = review.get("rich_spec_review", {})
    lines: List[str] = []
    lines.append("# 05 Critic Review")
    lines.append("")
    lines.append(f"**Agent:** `{AGENT_NAME}`")
    lines.append(f"**Schema:** `{review.get('schema_version')}`")
    lines.append(f"**Review status:** `{review.get('review_status')}`")
    lines.append(f"**Target function:** `{review.get('target_function')}`")
    lines.append(f"**Harness function:** `{review.get('harness_function')}`")
    lines.append(f"**Artifact:** `{review.get('artifact')}`")
    lines.append(f"**Iteration:** `{review.get('iteration')}`")
    lines.append("")
    lines.append("## Scientific guardrail")
    lines.append("")
    lines.append("This review does not prove the artifact correct. It only checks whether the candidate artifact is reasonable enough to send to the formal tool or whether repair is needed first. CBMC and human review remain the authority.")
    lines.append("")
    lines.append("## v2 spec-grounding checks")
    lines.append("")
    files_seen = rich.get("rich_context_files_seen", {}) if isinstance(rich, dict) else {}
    if files_seen:
        for key, value in files_seen.items():
            lines.append(f"- `{key}`: `{value}`")
    else:
        lines.append("- No rich v2 context summary available.")
    uncertainty = rich.get("uncertainty_review", {}) if isinstance(rich, dict) else {}
    if uncertainty:
        lines.append(f"- Uncertainty status: `{uncertainty.get('status')}` — {uncertainty.get('message')}")
    lines.append("")
    lines.append("## Quality metrics")
    lines.append("")
    lines.append(f"- Risk score: `{score.get('risk_score_0_to_100')}` / 100")
    lines.append(f"- Quality score: `{score.get('quality_score_0_to_100')}` / 100")
    lines.append(f"- Highest severity: `{score.get('highest_severity')}`")
    lines.append(f"- Issue count: `{score.get('issue_count')}`")
    lines.append("")
    lines.append("## Decision")
    lines.append("")
    lines.append(f"- Tool execution allowed: `{review.get('tool_execution_allowed')}`")
    lines.append(f"- Repair recommended before tool: `{review.get('repair_recommended_before_tool')}`")
    lines.append(f"- Human review required: `{review.get('human_review_required')}`")
    lines.append("")
    lines.append("## Issues")
    lines.append("")
    issues = as_list(review.get("issues"))
    if not issues:
        lines.append("No blocking issues detected by the deterministic critic. Human review is still required.")
    else:
        for i, it in enumerate(issues, start=1):
            lines.append(f"### {i}. `{it.get('severity')}` — `{it.get('type')}`")
            lines.append("")
            lines.append(str(it.get("message", "")))
            lines.append("")
            lines.append(f"**Recommended fix:** {it.get('recommendation', '')}")
            ev = it.get("evidence")
            if isinstance(ev, dict) and ev.get("text"):
                lines.append("")
                lines.append(f"Evidence line {ev.get('start_line')}: `{ev.get('text')}`")
            lines.append("")
    lines.append("## Positive findings")
    lines.append("")
    positives = as_list(review.get("positive_findings"))
    if positives:
        for item in positives:
            lines.append(f"- {item}")
    else:
        lines.append("- No positive findings recorded.")
    lines.append("")
    lines.append("## Property coverage")
    lines.append("")
    coverage = as_list(review.get("property_coverage"))
    if coverage:
        lines.append("| Property | Type | Coverage | Covered by |")
        lines.append("|---|---|---|---|")
        for c in coverage:
            covered_by = ", ".join(as_list(c.get("covered_by")))
            lines.append(f"| `{c.get('property_id')}` | `{c.get('property_type')}` | `{c.get('coverage_status')}` | {covered_by} |")
    else:
        lines.append("No selected property coverage map available.")
    lines.append("")
    lines.append("## Next recommended action")
    lines.append("")
    lines.append(str(review.get("next_recommended_action", "Human review required.")))
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main agent
# ---------------------------------------------------------------------------

def determine_artifact_path(run_dir: Path, project_root: Path, config: Dict[str, Any], args: argparse.Namespace) -> Path:
    if args.artifact:
        p = Path(args.artifact).expanduser()
        if not p.is_absolute():
            p = run_dir / p if len(p.parts) == 1 else project_root / p
        return p.resolve()

    status = read_json(run_dir / "status.json", default={})
    current = status.get("current_artifact") or config.get("current_artifact")
    if current:
        p = Path(str(current)).expanduser()
        if not p.is_absolute():
            p = run_dir / p if len(p.parts) == 1 else project_root / p
        return p.resolve()

    return (run_dir / DEFAULT_ARTIFACT).resolve()


def maybe_find_manifest(run_dir: Path, artifact_path: Path) -> Path:
    candidates = [
        run_dir / "04_artifact_manifest.json",
        run_dir / "04_generated_artifact_notes.json",
        artifact_path.with_suffix(".manifest.json"),
    ]
    for p in candidates:
        if p.exists():
            return p
    return run_dir / "04_artifact_manifest.json"


def run_agent(args: argparse.Namespace) -> int:
    started_at = utc_now()
    config_path = Path(args.config).expanduser().resolve()
    project_root = find_project_root(config_path)
    config = read_json(config_path)

    run_dir = Path(args.run_dir).expanduser() if args.run_dir else None
    if run_dir is None:
        run_id = str(config.get("run_id") or "run_001")
        run_dir = project_root / "runs" / run_id
    elif not run_dir.is_absolute():
        run_dir = project_root / run_dir
    run_dir = run_dir.resolve()
    run_dir.mkdir(parents=True, exist_ok=True)

    events_path = run_dir / "events.jsonl"
    append_jsonl(events_path, {
        "time": started_at,
        "agent": AGENT_NAME,
        "event_type": "started",
        "run_dir": str(run_dir),
        "config": str(config_path),
        "iteration": args.iteration,
        "schema_version": SCHEMA_VERSION,
    })

    spec_path = run_dir / "01_spec_summary.json"
    code_path = run_dir / "02_code_summary.json"
    props_path = run_dir / "03_candidate_properties.json"

    artifact_path = determine_artifact_path(run_dir, project_root, config, args)
    manifest_path = maybe_find_manifest(run_dir, artifact_path)

    spec_summary = read_json(spec_path, default={})
    code_summary = read_json(code_path, default={})
    properties = read_json(props_path, default={})
    manifest = read_json(manifest_path, default={})
    rich = load_rich_context(run_dir)
    artifact_text = read_text_if_exists(artifact_path)

    prompt_text = build_prompt_record(config, spec_summary, code_summary, properties, manifest, rich, artifact_text, artifact_path)
    prompt_path = run_dir / "llm_prompts" / "05_critic_review_prompt.txt"
    write_text(prompt_path, prompt_text)

    extracted = run_critic_rules(
        artifact_path=artifact_path,
        artifact_text=artifact_text,
        config=config,
        spec_summary=spec_summary,
        code_summary=code_summary,
        properties=properties,
        manifest=manifest,
        rich=rich,
        iteration=args.iteration,
    )

    issues = as_list(extracted.get("issues"))
    artifact_exists = artifact_path.exists() and bool(artifact_text.strip())
    review_status = review_status_from_issues(issues, artifact_exists)
    quality_metrics = score_from_issues(issues)

    blocking = any(str(i.get("severity", "")).lower() in {"critical", "high"} for i in issues)
    tool_allowed = artifact_exists and not blocking
    repair_before_tool = artifact_exists and blocking

    if not artifact_exists:
        next_action = "Re-run Formal Artifact Generation Agent before attempting CBMC."
    elif repair_before_tool:
        next_action = "Send the artifact to Repair / Refinement Agent before CBMC because high/critical critic issues were found."
    elif review_status == "conditional_accept_for_tool":
        next_action = "Artifact may go to Formal Tool Execution Agent, but preserve critic warnings for counterexample analysis and human review."
    else:
        next_action = "Artifact may go to Formal Tool Execution Agent; human review is still required."

    rich_reviews = extracted.get("rich_reviews", {})

    review: Dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "agent": AGENT_NAME,
        "created_at": utc_now(),
        "started_at": started_at,
        "finished_at": utc_now(),
        "iteration": args.iteration,
        "review_status": review_status,
        "status": review_status,
        "artifact": str(artifact_path),
        "artifact_sha256_16": sha256_short(artifact_text) if artifact_text else None,
        "artifact_exists": artifact_exists,
        "artifact_manifest": str(manifest_path),
        "input_files": {
            "config": str(config_path),
            "spec_summary": str(spec_path),
            "code_summary": str(code_path),
            "candidate_properties": str(props_path),
            "artifact_manifest": str(manifest_path),
            "artifact": str(artifact_path),
            "rich_agent2v2_files": {
                "algorithm_blocks": str(run_dir / "01_algorithm_blocks.json"),
                "symbol_table": str(run_dir / "01_symbol_table.json"),
                "parameter_table": str(run_dir / "01_parameter_table.json"),
                "equations_constraints": str(run_dir / "01_equations_constraints.json"),
                "preconditions_postconditions": str(run_dir / "01_preconditions_postconditions.json"),
                "spec_to_code_hints": str(run_dir / "01_spec_to_code_hints.json"),
            },
            "rich_agent4v2_files": {
                "spec_code_traceability": str(run_dir / "03_spec_code_traceability.json"),
                "integration_report": str(run_dir / "03_agent2v2_integration_report.json"),
                "property_evidence_matrix": str(run_dir / "03_property_evidence_matrix.csv"),
            },
            "rich_agent5v2_files": {
                "spec_grounding_report": str(run_dir / "04_spec_grounding_report.json"),
                "assertion_plan": str(run_dir / "04_spec_grounded_assertion_plan.json"),
                "assumption_traceability": str(run_dir / "04_harness_assumption_traceability.csv"),
            },
        },
        "target_function": extracted.get("target_function"),
        "harness_function": extracted.get("harness_function"),
        "selected_property_types": extracted.get("selected_property_types", []),
        "selected_property_ids": extracted.get("selected_property_ids", []),
        "review_checklist": extracted.get("checklist", []),
        "issues": issues,
        "recommended_fix": [i.get("recommendation") for i in issues if i.get("recommendation")],
        "positive_findings": extracted.get("positive_findings", []),
        "quality_metrics": quality_metrics,
        "tool_execution_allowed": tool_allowed,
        "repair_recommended_before_tool": repair_before_tool,
        "human_review_required": True,
        "next_recommended_action": next_action,
        "assumption_review": {
            "count": len(as_list(extracted.get("assumptions"))),
            "assumptions": extracted.get("assumptions", []),
        },
        "assertion_review": {
            "count": len(as_list(extracted.get("assertions"))),
            "assertions": extracted.get("assertions", []),
        },
        "cbmc_readiness": {
            "manifest_command_seen": extracted.get("manifest_command_seen", ""),
            "target_call_count": len(as_list(extracted.get("target_calls"))),
            "loop_count": len(as_list(extracted.get("loops"))),
            "array_access_count": len(as_list(extracted.get("array_accesses"))),
            "nondet_input_count": len(as_list(extracted.get("nondet_uses"))),
            "spec_constants_seen": extracted.get("spec_constants_seen", {}),
        },
        "property_coverage": extracted.get("property_coverage", []),
        "rich_spec_review": rich_reviews,
        "scientific_guardrail": {
            "claim": "This review does not prove correctness; it reviews candidate artifact quality before CBMC and human inspection.",
            "llm_or_deterministic": "deterministic_static_review_with_fips_aware_traceability",
            "formal_tool_and_human_are_authority": True,
        },
    }

    review_path = run_dir / "05_critic_review.json"
    md_path = run_dir / "05_critic_review.md"
    status_path = run_dir / "agent_status" / "05_critic_review_status.json"

    spec_grounding_review_path = run_dir / "05_spec_grounding_review.json"
    assumption_csv_path = run_dir / "05_assumption_evidence_review.csv"
    assertion_csv_path = run_dir / "05_assertion_algorithm_alignment.csv"
    symbol_uncertainty_path = run_dir / "05_symbol_uncertainty_review.json"

    write_json(review_path, review)
    write_text(md_path, render_markdown(review))
    write_json(spec_grounding_review_path, rich_reviews)
    write_csv(assumption_csv_path, as_list(rich_reviews.get("assumption_evidence_review")), fieldnames=["line", "expression", "classification", "traceability_status", "traceability_source"])
    write_csv(assertion_csv_path, as_list(rich_reviews.get("assertion_algorithm_alignment")), fieldnames=["line", "assertion", "alignment_status", "best_algorithm", "best_algorithm_step", "score", "note", "evidence"])
    write_json(symbol_uncertainty_path, {
        "symbol_misuse_findings": rich_reviews.get("symbol_misuse_findings", []),
        "uncertainty_review": rich_reviews.get("uncertainty_review", {}),
        "rich_context_files_seen": rich_reviews.get("rich_context_files_seen", {}),
    })

    write_json(status_path, {
        "agent": AGENT_NAME,
        "schema_version": SCHEMA_VERSION,
        "status": "passed" if artifact_exists else "failed",
        "review_status": review_status,
        "tool_execution_allowed": tool_allowed,
        "repair_recommended_before_tool": repair_before_tool,
        "started_at": started_at,
        "finished_at": review["finished_at"],
        "outputs": {
            "review_json": str(review_path),
            "review_markdown": str(md_path),
            "prompt": str(prompt_path),
            "spec_grounding_review": str(spec_grounding_review_path),
            "assumption_evidence_review": str(assumption_csv_path),
            "assertion_algorithm_alignment": str(assertion_csv_path),
            "symbol_uncertainty_review": str(symbol_uncertainty_path),
        },
        "human_review_required": True,
    })

    append_jsonl(events_path, {
        "time": utc_now(),
        "agent": AGENT_NAME,
        "event_type": "finished",
        "status": "ok" if artifact_exists else "failed",
        "review_status": review_status,
        "iteration": args.iteration,
        "issue_count": len(issues),
        "highest_severity": quality_metrics.get("highest_severity"),
        "tool_execution_allowed": tool_allowed,
        "outputs": {
            "review_json": str(review_path),
            "review_markdown": str(md_path),
            "spec_grounding_review": str(spec_grounding_review_path),
            "assumption_evidence_review": str(assumption_csv_path),
            "assertion_algorithm_alignment": str(assertion_csv_path),
            "symbol_uncertainty_review": str(symbol_uncertainty_path),
            "prompt": str(prompt_path),
        },
    })

    print(f"[OK] Review / Critic Agent v2 wrote: {review_path}")
    print(f"[OK] Markdown review: {md_path}")
    print(f"[OK] Spec grounding review: {spec_grounding_review_path}")
    print(f"[OK] Assumption evidence review: {assumption_csv_path}")
    print(f"[OK] Assertion algorithm alignment: {assertion_csv_path}")
    print(f"[INFO] Review status: {review_status}")
    print(f"[INFO] Issues: {len(issues)} | Highest severity: {quality_metrics.get('highest_severity')}")
    print(f"[INFO] Tool execution allowed: {tool_allowed}")
    print("[NOTE] This is a critic review only; CBMC and human review remain the authority.")

    return 0 if artifact_exists else 2


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Agent 6: Review / Critic Agent v2")
    parser.add_argument("--config", required=True, help="Path to run config JSON, e.g., configs/poly_add_run.json")
    parser.add_argument("--run-dir", required=False, help="Run directory, e.g., runs/run_001_poly_add")
    parser.add_argument("--iteration", type=int, default=0, help="Refinement iteration number")
    parser.add_argument("--artifact", required=False, help="Optional artifact filename/path to review, e.g., 04_generated_harness.c")
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    try:
        return run_agent(args)
    except Exception as exc:
        print(f"[ERROR] Review / Critic Agent v2 failed: {exc}", file=sys.stderr)
        print(traceback.format_exc(), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
