#!/usr/bin/env python3
"""Structured CBMC JSON evidence parsing and result classification."""
from __future__ import annotations

import json
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

from agents.common.tool_result_contract import (
    ANALYSIS_ONLY, CONTRACT_BUILD_FAILED, DRY_RUN_NOT_EXECUTED,
    SELECTED_PROPERTY_VERIFIED, SELECTED_PROPERTY_PASSED_AUXILIARY_FAILED, SKIPPED_BY_REVIEW_GATE, TOOL_ERROR_NO_PROPERTY_EVIDENCE,
    TOOL_EXECUTION_OR_EVIDENCE_INCONSISTENT, TOOL_OUTPUT_NOT_STRUCTURED_JSON, TOOL_SUCCESS_NO_EMITTED_EVIDENCE,
    TOOL_SUCCESS_NO_SELECTED_EVIDENCE, TOOL_TIMEOUT, TOOL_UNAVAILABLE, VERIFICATION_FAILED_OR_UNKNOWN,
)

JsonDict = Dict[str, Any]


def ensure_json_ui(command: Sequence[str]) -> List[str]:
    cmd = [str(x) for x in command]
    if not cmd:
        return cmd
    tool = cmd[0].rsplit("/", 1)[-1]
    if tool == "cbmc" and "--json-ui" not in cmd:
        cmd.append("--json-ui")
    return cmd


def _walk(value: Any) -> Iterable[Mapping[str, Any]]:
    if isinstance(value, Mapping):
        yield value
        for child in value.values():
            yield from _walk(child)
    elif isinstance(value, list):
        for child in value:
            yield from _walk(child)


def _status(value: Any) -> Optional[str]:
    text = str(value or "").strip().upper()
    aliases = {
        "PASS": "SUCCESS", "PASSED": "SUCCESS", "SUCCESSFUL": "SUCCESS",
        "FAIL": "FAILURE", "FAILED": "FAILURE", "ERROR": "ERROR",
        "UNKNOWN": "UNKNOWN", "SUCCESS": "SUCCESS", "FAILURE": "FAILURE",
    }
    return aliases.get(text)


def parse_cbmc_json_output(stdout: str, stderr: str = "") -> JsonDict:
    """Parse CBMC ``--json-ui`` output without relying on human-readable text."""
    raw = stdout.strip()
    if not raw:
        return {
            "schema_version": "cbmc_structured_results.v1",
            "json_valid": False,
            "parse_error": "CBMC stdout was empty.",
            "property_results": [],
            "property_result_count": 0,
            "success_count": 0,
            "failure_count": 0,
            "unknown_count": 0,
            "messages": [],
        }
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        return {
            "schema_version": "cbmc_structured_results.v1",
            "json_valid": False,
            "parse_error": f"JSONDecodeError line {exc.lineno} column {exc.colno}: {exc.msg}",
            "property_results": [],
            "property_result_count": 0,
            "success_count": 0,
            "failure_count": 0,
            "unknown_count": 0,
            "messages": [],
            "stderr_excerpt": stderr[:4000],
        }

    rows: List[JsonDict] = []
    messages: List[JsonDict] = []
    for node in _walk(data):
        status = _status(node.get("status") or node.get("result") or node.get("propertyStatus"))
        prop_id = (
            node.get("property") or node.get("propertyId") or node.get("property_id")
            or node.get("name") if status else None
        )
        # CBMC result entries commonly have property, status, description,
        # sourceLocation, and trace fields. Avoid treating generic messages as
        # properties unless a status and an identifier/description are present.
        description = node.get("description") or node.get("messageText") or node.get("message")
        if status and (prop_id or description):
            source = node.get("sourceLocation") or node.get("source_location") or {}
            rows.append({
                "property": str(prop_id or "unnamed_property"),
                "property_id": str(prop_id or "unnamed_property"),
                "status": status,
                "description": str(description or ""),
                "source_location": source,
                "trace_present": bool(node.get("trace")),
            })
        message_type = node.get("messageType") or node.get("message_type")
        message_text = node.get("messageText") or node.get("message")
        if message_type or message_text:
            messages.append({
                "message_type": str(message_type or ""),
                "message_text": str(message_text or ""),
            })

    # Preserve order while removing exact duplicates generated by recursive walk.
    unique: List[JsonDict] = []
    seen = set()
    for row in rows:
        key = (row["property_id"], row["status"], row["description"], json.dumps(row["source_location"], sort_keys=True, default=str))
        if key not in seen:
            seen.add(key)
            unique.append(row)

    successes = [r for r in unique if r["status"] == "SUCCESS"]
    failures = [r for r in unique if r["status"] in {"FAILURE", "ERROR"}]
    unknown = [r for r in unique if r["status"] == "UNKNOWN"]
    return {
        "schema_version": "cbmc_structured_results.v1",
        "json_valid": True,
        "parse_error": None,
        "property_results": unique,
        "property_result_count": len(unique),
        "success_count": len(successes),
        "failure_count": len(failures),
        "unknown_count": len(unknown),
        "failed_properties": failures,
        "messages": messages[:500],
        "raw_json_top_level_type": type(data).__name__,
    }


def _mapped_selected_rows(coverage: Mapping[str, Any]) -> List[JsonDict]:
    rows: List[JsonDict] = []
    for mapped in coverage.get("mapped_claims", []) if isinstance(coverage.get("mapped_claims"), list) else []:
        if not isinstance(mapped, Mapping):
            continue
        for match in mapped.get("matches", []) if isinstance(mapped.get("matches"), list) else []:
            if isinstance(match, Mapping) and isinstance(match.get("row"), Mapping):
                rows.append(dict(match["row"]))
            elif isinstance(match, Mapping):
                rows.append(dict(match))
    return rows


def _status_summary(rows: Sequence[Mapping[str, Any]], *, missing_label: str) -> str:
    if not rows:
        return missing_label
    statuses = {str(row.get("status") or "UNKNOWN").upper() for row in rows}
    has_success = "SUCCESS" in statuses
    has_failure = bool(statuses & {"FAILURE", "ERROR"})
    has_unknown = "UNKNOWN" in statuses or bool(statuses - {"SUCCESS", "FAILURE", "ERROR", "UNKNOWN"})
    if has_failure and (has_success or has_unknown):
        return "mixed"
    if has_failure:
        return "failed"
    if has_unknown and has_success:
        return "mixed"
    if has_unknown:
        return "unknown"
    if has_success:
        return "passed"
    return "unknown"


def _rows_with_status(rows: Sequence[Mapping[str, Any]], statuses: set[str]) -> List[JsonDict]:
    return [dict(row) for row in rows if str(row.get("status") or "UNKNOWN").upper() in statuses]


def _compact_rows(rows: Sequence[Mapping[str, Any]]) -> List[JsonDict]:
    return [
        {
            "property_id": str(row.get("property_id") or row.get("property") or ""),
            "status": str(row.get("status") or "UNKNOWN").upper(),
            "description": str(row.get("description") or ""),
            "source_location": row.get("source_location") or {},
            "trace_present": bool(row.get("trace_present")),
        }
        for row in rows
    ]


def classify_evidence(
    *,
    executed: bool,
    exit_code: Optional[int],
    timeout: bool,
    skipped: bool,
    dry_run: bool,
    unavailable: bool,
    analysis_only: bool,
    pipeline_setup_failed: bool,
    structured: Mapping[str, Any],
    coverage: Mapping[str, Any],
) -> JsonDict:
    """Classify exact selected-claim evidence independently from auxiliary checks.

    CBMC commonly returns a non-zero exit code when *any* property fails.  That
    process-level signal must not collapse a passing selected thesis claim into
    a selected-claim failure when only auxiliary safety/model checks failed.
    """
    invocation_completed = bool(executed and not timeout and not unavailable and not pipeline_setup_failed)
    process_exit_zero = bool(invocation_completed and exit_code == 0)
    structured_valid = bool(structured.get("json_valid"))
    all_rows = [dict(row) for row in structured.get("property_results", []) if isinstance(row, Mapping)]
    property_count = len(all_rows)
    failure_count = int(structured.get("failure_count") or 0)
    unknown_count = int(structured.get("unknown_count") or 0)
    selected_rows = _mapped_selected_rows(coverage)
    selected_keys = {json.dumps(row, sort_keys=True, default=str) for row in selected_rows}
    auxiliary_rows = [row for row in all_rows if json.dumps(row, sort_keys=True, default=str) not in selected_keys]
    coverage_complete = bool(coverage.get("coverage_complete"))

    selected_claim_result = _status_summary(selected_rows, missing_label="not_generated")
    if not coverage_complete:
        selected_claim_result = "not_generated" if not selected_rows else "incomplete_or_ambiguous"
    auxiliary_property_result = _status_summary(auxiliary_rows, missing_label="not_emitted")

    selected_failed = _rows_with_status(selected_rows, {"FAILURE", "ERROR"})
    selected_unknown = _rows_with_status(selected_rows, {"UNKNOWN"})
    auxiliary_failed = _rows_with_status(auxiliary_rows, {"FAILURE", "ERROR"})
    auxiliary_unknown = _rows_with_status(auxiliary_rows, {"UNKNOWN"})
    all_emitted_success = bool(structured_valid and property_count > 0 and not selected_failed and not selected_unknown and not auxiliary_failed and not auxiliary_unknown)

    if analysis_only:
        classification = ANALYSIS_ONLY
        reason = "Configured campaign is analysis-only."
    elif skipped:
        classification = SKIPPED_BY_REVIEW_GATE
        reason = "Reviewed execution was not approved."
    elif dry_run:
        classification = DRY_RUN_NOT_EXECUTED
        reason = "Dry run produced no formal-tool evidence."
    elif unavailable:
        classification = TOOL_UNAVAILABLE
        reason = "The configured formal tool was unavailable."
    elif timeout:
        classification = TOOL_TIMEOUT
        reason = "Formal-tool execution timed out."
    elif pipeline_setup_failed:
        classification = CONTRACT_BUILD_FAILED
        reason = "The planned compile/instrumentation pipeline did not reach authoritative CBMC execution."
    elif not structured_valid:
        classification = TOOL_OUTPUT_NOT_STRUCTURED_JSON if invocation_completed else TOOL_ERROR_NO_PROPERTY_EVIDENCE
        reason = "Authoritative CBMC output was not valid structured JSON."
    elif property_count <= 0:
        classification = TOOL_SUCCESS_NO_EMITTED_EVIDENCE if process_exit_zero else TOOL_ERROR_NO_PROPERTY_EVIDENCE
        reason = "No structured CBMC property rows were emitted."
    elif not coverage_complete:
        classification = TOOL_SUCCESS_NO_SELECTED_EVIDENCE
        reason = "CBMC emitted properties, but exact selected-claim mapping is incomplete or ambiguous."
    elif selected_claim_result in {"failed", "mixed", "unknown"}:
        classification = VERIFICATION_FAILED_OR_UNKNOWN
        reason = "At least one exactly mapped selected claim failed or was unknown."
    elif selected_claim_result == "passed" and auxiliary_property_result in {"failed", "mixed", "unknown"}:
        classification = SELECTED_PROPERTY_PASSED_AUXILIARY_FAILED
        reason = "Every exactly mapped selected claim passed, but one or more auxiliary properties failed or were unknown."
    elif selected_claim_result == "passed" and process_exit_zero:
        classification = SELECTED_PROPERTY_VERIFIED
        reason = "Every exactly mapped selected claim succeeded under the recorded harness, assumptions, command, and model."
    else:
        classification = TOOL_EXECUTION_OR_EVIDENCE_INCONSISTENT
        reason = "Tool exit status, structured properties, and exact selected-claim mapping were not mutually consistent."

    if not invocation_completed:
        overall_model_result = "not_executed_or_incomplete"
    elif auxiliary_failed or selected_failed:
        overall_model_result = "verification_failed"
    elif auxiliary_unknown or selected_unknown:
        overall_model_result = "verification_unknown"
    elif all_emitted_success and process_exit_zero:
        overall_model_result = "verification_success"
    else:
        overall_model_result = "incomplete_or_inconsistent"

    return {
        "schema_version": "formal_evidence_classification.v2",
        "result_classification": classification,
        "result_reason": reason,
        "tool_invocation_completed": invocation_completed,
        "tool_execution_successful": process_exit_zero,
        "process_exit_zero": process_exit_zero,
        "structured_json_valid": structured_valid,
        "cbmc_reported_all_emitted_properties_successful": all_emitted_success,
        "selected_property_coverage_complete": coverage_complete,
        "selected_property_verified_under_model": selected_claim_result == "passed",
        "selected_claim_result": selected_claim_result,
        "selected_claim_property_count": len(selected_rows),
        "selected_failed_property_count": len(selected_failed),
        "selected_unknown_property_count": len(selected_unknown),
        "selected_failed_properties": _compact_rows(selected_failed),
        "selected_unknown_properties": _compact_rows(selected_unknown),
        "auxiliary_property_result": auxiliary_property_result,
        "auxiliary_property_count": len(auxiliary_rows),
        "auxiliary_failed_property_count": len(auxiliary_failed),
        "auxiliary_unknown_property_count": len(auxiliary_unknown),
        "auxiliary_failed_properties": _compact_rows(auxiliary_failed),
        "auxiliary_unknown_properties": _compact_rows(auxiliary_unknown),
        "overall_model_result": overall_model_result,
        "emitted_property_count": property_count,
        "emitted_failure_count": failure_count,
        "emitted_unknown_count": unknown_count,
        "claim_boundary": {
            "selected_claim_result_is_independent_of_auxiliary_checks": True,
            "overall_model_success_requires_all_emitted_properties_successful": True,
            "nonzero_exit_alone_does_not_identify_which_claim_failed": True,
        },
    }


__all__ = ["classify_evidence", "ensure_json_ui", "parse_cbmc_json_output"]
