#!/usr/bin/env python3
"""
Agent 6: Review / Critic Agent
==============================

Purpose
-------
This agent reviews the candidate formal-verification artifact generated by Agent 5.
For the current thesis prototype, the artifact is usually a CBMC C harness:

  04_generated_harness.c

The critic reads:
  - 04_generated_harness.c (or the current artifact passed by the orchestrator)
  - 04_artifact_manifest.json
  - 01_spec_summary.json
  - 02_code_summary.json
  - 03_candidate_properties.json
  - config JSON

It produces:
  - 05_critic_review.json
  - 05_critic_review.md
  - llm_prompts/05_critic_review_prompt.txt
  - agent_status/05_critic_review_status.json

Scientific guardrail
--------------------
This agent DOES NOT prove the artifact correct. It is a deterministic reviewer that catches
obvious and common artifact problems before CBMC/formal-tool execution. CBMC and human
review remain the authority.

Design goals
------------
- Standard-library only.
- Deterministic and reproducible.
- Conservative: severe structural problems block tool execution; warnings are preserved.
- Compatible with the Master Orchestrator's decision logic.
- Produces both human-readable and machine-readable review output.

Typical use
-----------
python3 agents/review_critic_agent.py \
  --config configs/poly_add_run.json \
  --run-dir runs/run_001_poly_add \
  --iteration 0
"""

from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple


AGENT_NAME = "review_critic_agent"
SCHEMA_VERSION = "1.0"
DEFAULT_ARTIFACT = "04_generated_harness.c"


# ---------------------------------------------------------------------------
# Basic IO helpers
# ---------------------------------------------------------------------------


def utc_now() -> str:
    return _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds")


def read_json(path: Path, default: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    if not path.exists():
        if default is not None:
            return default
        raise FileNotFoundError(f"Required JSON file not found: {path}")
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"Expected JSON object in {path}, got {type(data).__name__}")
    return data


def write_json(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")
    tmp.replace(path)


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def append_jsonl(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(data, ensure_ascii=False) + "\n")


def sha256_short(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", errors="replace")).hexdigest()[:16]


def read_text_if_exists(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except FileNotFoundError:
        return ""


def as_list(value: Any) -> List[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def normalize_space(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def strip_c_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//.*?$", "", text, flags=re.M)
    return text


def find_project_root(config_path: Path) -> Path:
    parent = config_path.resolve().parent
    if parent.name == "configs":
        return parent.parent
    return parent


def resolve_path(project_root: Path, maybe_path: Optional[str], fallback: Optional[Path] = None) -> Path:
    if maybe_path:
        p = Path(maybe_path).expanduser()
        if not p.is_absolute():
            p = project_root / p
        return p.resolve()
    if fallback is None:
        raise ValueError("Missing required path and no fallback provided")
    return fallback.resolve()


# ---------------------------------------------------------------------------
# C/harness extraction helpers
# ---------------------------------------------------------------------------


def indexed_lines(text: str) -> List[Tuple[int, str]]:
    return list(enumerate(text.splitlines(), start=1))


def evidence_for_line(path: Path, line_no: int, line: str) -> Dict[str, Any]:
    return {
        "source_file": str(path),
        "start_line": line_no,
        "end_line": line_no,
        "text": line.strip(),
    }


def find_lines_matching(text: str, pattern: str, flags: int = 0) -> List[Tuple[int, str, re.Match[str]]]:
    out: List[Tuple[int, str, re.Match[str]]] = []
    rx = re.compile(pattern, flags)
    for line_no, line in indexed_lines(text):
        m = rx.search(line)
        if m:
            out.append((line_no, line, m))
    return out


def extract_assumptions(text: str, path: Path) -> List[Dict[str, Any]]:
    assumptions: List[Dict[str, Any]] = []
    # Handles one-line __CPROVER_assume(expr); and common spacing.
    for line_no, line, m in find_lines_matching(text, r"__CPROVER_assume\s*\((.*)\)\s*;"):
        expr = normalize_space(m.group(1))
        assumptions.append(
            {
                "expression": expr,
                "line": line_no,
                "evidence": evidence_for_line(path, line_no, line),
                "classification": classify_assumption(expr),
            }
        )
    return assumptions


def extract_assertions(text: str, path: Path) -> List[Dict[str, Any]]:
    assertions: List[Dict[str, Any]] = []
    for line_no, line, m in find_lines_matching(text, r"\bassert\s*\((.*)\)\s*;"):
        expr = normalize_space(m.group(1))
        assertions.append(
            {
                "expression": expr,
                "line": line_no,
                "evidence": evidence_for_line(path, line_no, line),
                "classification": classify_assertion(expr),
            }
        )
    return assertions


def classify_assumption(expr: str) -> str:
    e = expr.replace(" ", "").lower()
    if e in {"0", "false", "(0)", "(false)"}:
        return "contradictory_or_vacuous"
    if e in {"1", "true", "(1)", "(true)"}:
        return "trivial"
    if re.search(r"coeffs\s*\[.*?\]\s*(<=|<|>=|>)\s*-?\d+", expr):
        return "coefficient_numeric_bound"
    if re.search(r"\w+\s*!=\s*null|\w+\s*!=\s*0", expr, re.I):
        return "pointer_non_null"
    if re.search(r"\w+\s*<\s*\w+|\w+\s*<=\s*\w+", expr):
        return "relational_bound"
    return "general_assumption"


def classify_assertion(expr: str) -> str:
    e = expr.replace(" ", "").lower()
    if e in {"1", "true", "(1)", "(true)"}:
        return "trivial"
    if e in {"0", "false", "(0)", "(false)"}:
        return "always_fails"
    if "==" in expr and "coeffs" in expr:
        return "coefficient_functional_equality"
    if "<" in expr or ">" in expr:
        return "range_or_bounds_assertion"
    return "general_assertion"


def extract_function_calls(text: str) -> List[Dict[str, Any]]:
    clean = strip_c_comments(text)
    calls: List[Dict[str, Any]] = []
    # Intentionally simple. We filter keywords and declarations later.
    keywords = {
        "if", "for", "while", "switch", "return", "sizeof", "assert", "__CPROVER_assume",
        "harness_poly_add", "void", "int", "uint16_t", "int16_t", "uint32_t", "int32_t",
    }
    for line_no, line in indexed_lines(clean):
        for m in re.finditer(r"\b([A-Za-z_]\w*)\s*\(", line):
            name = m.group(1)
            if name in keywords:
                continue
            # Skip function definition line if it starts with return type and has opening brace.
            if re.search(rf"\b{name}\s*\([^;]*\)\s*\{{", line):
                continue
            calls.append({"name": name, "line": line_no, "text": normalize_space(line)})
    return calls


def extract_includes(text: str, path: Path) -> List[Dict[str, Any]]:
    includes: List[Dict[str, Any]] = []
    for line_no, line, m in find_lines_matching(text, r"^\s*#\s*include\s*([<\"].*[>\"])"):
        includes.append(
            {
                "include": m.group(1),
                "line": line_no,
                "evidence": evidence_for_line(path, line_no, line),
            }
        )
    return includes


def extract_loops(text: str, path: Path) -> List[Dict[str, Any]]:
    loops: List[Dict[str, Any]] = []
    for line_no, line, m in find_lines_matching(text, r"\bfor\s*\((.*?)\)"):
        raw = normalize_space(m.group(1))
        parts = [p.strip() for p in raw.split(";")]
        loops.append(
            {
                "kind": "for",
                "raw": raw,
                "init": parts[0] if len(parts) > 0 else "",
                "condition": parts[1] if len(parts) > 1 else "",
                "increment": parts[2] if len(parts) > 2 else "",
                "line": line_no,
                "evidence": evidence_for_line(path, line_no, line),
            }
        )
    for line_no, line, m in find_lines_matching(text, r"\bwhile\s*\((.*?)\)"):
        loops.append(
            {
                "kind": "while",
                "raw": normalize_space(m.group(1)),
                "condition": normalize_space(m.group(1)),
                "line": line_no,
                "evidence": evidence_for_line(path, line_no, line),
            }
        )
    return loops


def extract_array_accesses(text: str, path: Path) -> List[Dict[str, Any]]:
    accesses: List[Dict[str, Any]] = []
    for line_no, line in indexed_lines(strip_c_comments(text)):
        for m in re.finditer(r"([A-Za-z_]\w*(?:->|\.)?[A-Za-z_]\w*)\s*\[\s*([^\]]+)\s*\]", line):
            accesses.append(
                {
                    "access": f"{m.group(1)}[{m.group(2).strip()}]",
                    "base": m.group(1),
                    "index": m.group(2).strip(),
                    "line": line_no,
                    "evidence": evidence_for_line(path, line_no, line),
                }
            )
    return accesses


def extract_nondet_uses(text: str, path: Path) -> List[Dict[str, Any]]:
    uses: List[Dict[str, Any]] = []
    for line_no, line, m in find_lines_matching(text, r"\b(nondet_[A-Za-z0-9_]+)\s*\("):
        uses.append(
            {
                "function": m.group(1),
                "line": line_no,
                "evidence": evidence_for_line(path, line_no, line),
            }
        )
    return uses


def harness_declares_function(text: str, harness_function: str) -> bool:
    if not harness_function:
        return False
    return re.search(rf"\bvoid\s+{re.escape(harness_function)}\s*\(", text) is not None


def target_call_present(text: str, target_function: str) -> List[Dict[str, Any]]:
    if not target_function:
        return []
    calls: List[Dict[str, Any]] = []
    rx = re.compile(rf"\b{re.escape(target_function)}\s*\(")
    for line_no, line in indexed_lines(strip_c_comments(text)):
        if rx.search(line):
            # Avoid counting function prototype/definition if line begins with return type and ends with semicolon?
            calls.append({"line": line_no, "evidence": evidence_for_line(Path("artifact"), line_no, line)})
    return calls


# ---------------------------------------------------------------------------
# Context extraction from previous agent outputs
# ---------------------------------------------------------------------------


def get_target_function(config: Dict[str, Any], code_summary: Dict[str, Any], manifest: Dict[str, Any]) -> str:
    return str(
        manifest.get("target_function")
        or code_summary.get("target_function_detected")
        or code_summary.get("target_function_requested")
        or config.get("target_function")
        or ""
    ).strip()


def get_harness_function(config: Dict[str, Any], manifest: Dict[str, Any], target_function: str) -> str:
    return str(
        manifest.get("harness_function")
        or config.get("harness_function")
        or (f"harness_{target_function}" if target_function else "")
    ).strip()


def get_spec_constants(spec_summary: Dict[str, Any]) -> Dict[str, Any]:
    constants = spec_summary.get("constants", {})
    if isinstance(constants, dict):
        return constants
    return {}


def constant_value(constants: Dict[str, Any], name: str) -> Optional[Any]:
    item = constants.get(name) or constants.get(name.upper()) or constants.get(name.lower())
    if isinstance(item, dict):
        return item.get("value")
    return item


def spec_has_supported_bound(spec_summary: Dict[str, Any]) -> bool:
    """Return True only when the spec summary explicitly mentions coefficient value bounds.

    q and N alone do not automatically justify a harness assumption like coeff >= -3329.
    We intentionally keep this conservative.
    """
    buckets = [
        "input_assumptions",
        "candidate_output_guarantees",
        "candidate_safety_properties",
        "candidate_functional_properties",
    ]
    bound_keywords = ["coefficient", "coeffs", "bound", "range", "between", "less than", "greater than", "<=", ">=", "valid input bound"]
    for bucket in buckets:
        for item in as_list(spec_summary.get(bucket)):
            text = json.dumps(item, ensure_ascii=False).lower() if isinstance(item, (dict, list)) else str(item).lower()
            if "coefficient" in text and any(k in text for k in bound_keywords) and re.search(r"[<>]=?|between", text):
                return True
    return False


def code_has_coeff_addition(code_summary: Dict[str, Any], artifact_text: str) -> bool:
    text = json.dumps(code_summary, ensure_ascii=False) + "\n" + artifact_text
    return bool(re.search(r"coeffs\s*\[.*?\].*\+.*coeffs\s*\[", text, flags=re.S))


def code_uses_signed_small_int(code_summary: Dict[str, Any], artifact_text: str) -> bool:
    text = (json.dumps(code_summary, ensure_ascii=False) + "\n" + artifact_text).lower()
    return any(token in text for token in ["int16_t", "int8_t", "signed", "nondet_int16_t", "nondet_int8_t"])


def selected_properties(properties: Dict[str, Any], manifest: Dict[str, Any]) -> List[Dict[str, Any]]:
    selected = manifest.get("selected_properties_used")
    if isinstance(selected, list):
        return [p for p in selected if isinstance(p, dict)]
    candidates = properties.get("candidate_properties")
    if isinstance(candidates, list):
        return [p for p in candidates if isinstance(p, dict)]
    return []


# ---------------------------------------------------------------------------
# Issue generation helpers
# ---------------------------------------------------------------------------


def issue(
    severity: str,
    issue_type: str,
    message: str,
    recommendation: str,
    evidence: Optional[Dict[str, Any]] = None,
    related_property_ids: Optional[List[str]] = None,
) -> Dict[str, Any]:
    data: Dict[str, Any] = {
        "severity": severity,
        "type": issue_type,
        "message": message,
        "recommendation": recommendation,
    }
    if evidence:
        data["evidence"] = evidence
    if related_property_ids:
        data["related_property_ids"] = related_property_ids
    return data


def highest_severity(issues: List[Dict[str, Any]]) -> str:
    rank = {"info": 0, "low": 1, "medium": 2, "high": 3, "critical": 4}
    if not issues:
        return "none"
    return max((str(i.get("severity", "info")).lower() for i in issues), key=lambda s: rank.get(s, 0))


def review_status_from_issues(issues: List[Dict[str, Any]], artifact_exists: bool) -> str:
    if not artifact_exists:
        return "reject"
    severities = [str(i.get("severity", "info")).lower() for i in issues]
    if "critical" in severities or "high" in severities:
        return "needs_revision"
    if "medium" in severities:
        # Important: the Master Orchestrator treats high/critical as blocking, and this status
        # lets the artifact go to CBMC while preserving warnings for later repair/reporting.
        return "conditional_accept_for_tool"
    return "accept_for_tool"


def score_from_issues(issues: List[Dict[str, Any]]) -> Dict[str, Any]:
    weights = {"critical": 40, "high": 25, "medium": 10, "low": 3, "info": 1}
    raw = sum(weights.get(str(i.get("severity", "info")).lower(), 1) for i in issues)
    risk = min(100, raw)
    quality = max(0, 100 - risk)
    return {
        "risk_score_0_to_100": risk,
        "quality_score_0_to_100": quality,
        "highest_severity": highest_severity(issues),
        "issue_count": len(issues),
        "severity_counts": {
            sev: sum(1 for i in issues if str(i.get("severity", "")).lower() == sev)
            for sev in ["critical", "high", "medium", "low", "info"]
        },
    }


# ---------------------------------------------------------------------------
# Critic rules
# ---------------------------------------------------------------------------


def run_critic_rules(
    *,
    artifact_path: Path,
    artifact_text: str,
    config: Dict[str, Any],
    spec_summary: Dict[str, Any],
    code_summary: Dict[str, Any],
    properties: Dict[str, Any],
    manifest: Dict[str, Any],
    iteration: int,
) -> Dict[str, Any]:
    target_function = get_target_function(config, code_summary, manifest)
    harness_function = get_harness_function(config, manifest, target_function)
    selected = selected_properties(properties, manifest)
    selected_types = sorted({str(p.get("type", "unknown")) for p in selected})
    selected_ids = [str(p.get("id")) for p in selected if p.get("id")]

    artifact_exists = artifact_path.exists() and bool(artifact_text.strip())
    issues: List[Dict[str, Any]] = []
    positives: List[str] = []
    checklist: List[Dict[str, Any]] = []

    assumptions = extract_assumptions(artifact_text, artifact_path) if artifact_exists else []
    assertions = extract_assertions(artifact_text, artifact_path) if artifact_exists else []
    includes = extract_includes(artifact_text, artifact_path) if artifact_exists else []
    loops = extract_loops(artifact_text, artifact_path) if artifact_exists else []
    array_accesses = extract_array_accesses(artifact_text, artifact_path) if artifact_exists else []
    nondet_uses = extract_nondet_uses(artifact_text, artifact_path) if artifact_exists else []
    calls = extract_function_calls(artifact_text) if artifact_exists else []
    target_calls = target_call_present(artifact_text, target_function) if artifact_exists else []

    constants = get_spec_constants(spec_summary)
    spec_n = constant_value(constants, "N")
    spec_q = constant_value(constants, "q")
    manifest_cmd = str(manifest.get("recommended_cbmc_command") or manifest.get("cbmc_command") or "")
    if not manifest_cmd:
        # Some generated manifests store commands in nested structure.
        manifest_cmd = json.dumps(manifest.get("recommended_commands", ""), ensure_ascii=False)

    def add_check(name: str, passed: bool, details: str, severity_if_failed: str = "medium") -> None:
        checklist.append({"check": name, "passed": passed, "details": details, "severity_if_failed": severity_if_failed})

    # 1. Artifact existence and basic shape.
    if not artifact_exists:
        issues.append(
            issue(
                "critical",
                "missing_artifact",
                f"The expected artifact file was not found or is empty: {artifact_path}",
                "Re-run the Formal Artifact Generation Agent and confirm that 04_generated_harness.c is created.",
            )
        )
        add_check("artifact_exists", False, "Artifact file missing or empty", "critical")
        return {
            "target_function": target_function,
            "harness_function": harness_function,
            "selected_property_types": selected_types,
            "selected_property_ids": selected_ids,
            "assumptions": assumptions,
            "assertions": assertions,
            "includes": includes,
            "loops": loops,
            "array_accesses": array_accesses,
            "nondet_uses": nondet_uses,
            "function_calls": calls,
            "issues": issues,
            "positive_findings": positives,
            "checklist": checklist,
        }

    add_check("artifact_exists", True, f"Artifact found: {artifact_path}", "critical")
    positives.append("Artifact file exists and is non-empty.")

    # 2. Guardrail comments.
    lower_artifact = artifact_text.lower()
    has_candidate_guardrail = "candidate" in lower_artifact and ("does not prove" in lower_artifact or "must be reviewed" in lower_artifact)
    add_check(
        "scientific_guardrail_comment",
        has_candidate_guardrail,
        "Harness states candidate/non-proof status" if has_candidate_guardrail else "Harness does not clearly state candidate/non-proof status",
        "low",
    )
    if has_candidate_guardrail:
        positives.append("Artifact includes a candidate/non-proof guardrail comment.")
    else:
        issues.append(
            issue(
                "low",
                "missing_scientific_guardrail_comment",
                "The harness does not clearly state that it is only a candidate artifact and not a proof.",
                "Add a short header comment saying the artifact must be reviewed by the Critic Agent, CBMC, and the human researcher.",
            )
        )

    # 3. Harness function existence.
    has_harness = harness_declares_function(artifact_text, harness_function)
    add_check(
        "harness_function_declared",
        has_harness,
        f"Expected harness function `{harness_function}` declared" if has_harness else f"Expected harness function `{harness_function}` not declared",
        "high",
    )
    if has_harness:
        positives.append(f"Expected harness function `{harness_function}` is declared.")
    else:
        issues.append(
            issue(
                "high",
                "missing_harness_function",
                f"The artifact does not declare the expected harness function `{harness_function}`.",
                "Generate or rename the harness function so the CBMC command can target it with --function.",
            )
        )

    # 4. Target function call.
    add_check(
        "target_function_called",
        bool(target_calls),
        f"Target function `{target_function}` call found" if target_calls else f"No call to target function `{target_function}` found",
        "high",
    )
    if target_calls:
        positives.append(f"Artifact calls the target function `{target_function}`.")
    else:
        issues.append(
            issue(
                "high",
                "missing_target_call",
                f"The harness does not call the selected target function `{target_function}`.",
                "Call the exact selected implementation function; otherwise CBMC may verify only the harness scaffolding.",
            )
        )

    # 5. Include and type sanity.
    include_names = [x.get("include", "") for x in includes]
    has_assert_include = any("assert.h" in s for s in include_names)
    add_check("assert_header_included", has_assert_include, "assert.h included" if has_assert_include else "assert.h not included", "medium")
    if assertions and not has_assert_include:
        issues.append(
            issue(
                "medium",
                "missing_assert_header",
                "The harness uses assert(...) but does not visibly include <assert.h>.",
                "Include <assert.h> or ensure the build environment provides assert declarations safely.",
            )
        )
    elif has_assert_include:
        positives.append("Harness includes <assert.h> for C assertions.")

    # 6. Assumption checks.
    contradictory_assumptions = [a for a in assumptions if a.get("classification") == "contradictory_or_vacuous"]
    for a in contradictory_assumptions:
        issues.append(
            issue(
                "critical",
                "vacuous_assumption",
                f"The assumption `{a['expression']}` can make the proof vacuous or unreachable.",
                "Remove contradictory assumptions; every assumption should represent a real precondition.",
                a.get("evidence"),
            )
        )

    coefficient_bound_assumptions = [a for a in assumptions if a.get("classification") == "coefficient_numeric_bound"]
    has_explicit_spec_bound = spec_has_supported_bound(spec_summary)
    for a in coefficient_bound_assumptions:
        if not has_explicit_spec_bound:
            issues.append(
                issue(
                    "high",
                    "unsupported_coefficient_bound_assumption",
                    f"The coefficient bound assumption `{a['expression']}` may not be justified by the selected specification excerpt alone.",
                    "Either cite a precise input-bound rule from the selected spec/code context, or move this assumption into a human-reviewed experiment variant.",
                    a.get("evidence"),
                )
            )
    if coefficient_bound_assumptions and has_explicit_spec_bound:
        positives.append("Coefficient numeric assumptions exist and the spec summary appears to contain explicit bound evidence.")
    elif not coefficient_bound_assumptions:
        positives.append("No unsupported default coefficient range assumptions were inserted by the harness.")

    add_check(
        "no_contradictory_assumptions",
        not contradictory_assumptions,
        "No obviously contradictory assumptions found" if not contradictory_assumptions else "Contradictory/vacuous assumptions found",
        "critical",
    )

    # 7. Assertion checks.
    if not assertions:
        # For memory-safety-only harnesses, this can be acceptable if CBMC builtin checks are planned.
        has_builtin_checks = any(flag in manifest_cmd for flag in ["--bounds-check", "--pointer-check", "--signed-overflow-check"])
        severity = "medium" if not has_builtin_checks else "low"
        issues.append(
            issue(
                severity,
                "no_explicit_assertions",
                "The harness has no explicit assert(...) statements.",
                "This is acceptable only if the selected properties are intentionally checked through CBMC built-in checks; document that clearly.",
            )
        )
    else:
        positives.append(f"Harness contains {len(assertions)} explicit assertion(s).")

    for a in assertions:
        cls = a.get("classification")
        if cls == "trivial":
            issues.append(
                issue(
                    "high",
                    "trivial_assertion",
                    f"The assertion `{a['expression']}` is trivial and does not check the selected implementation behavior.",
                    "Replace trivial assertions with property-connected assertions or rely on CBMC built-in checks explicitly.",
                    a.get("evidence"),
                )
            )
        elif cls == "always_fails":
            issues.append(
                issue(
                    "high",
                    "always_failing_assertion",
                    f"The assertion `{a['expression']}` always fails and is likely a harness mistake.",
                    "Replace it with a meaningful property assertion or remove it.",
                    a.get("evidence"),
                )
            )

    functional_assertions = [a for a in assertions if a.get("classification") == "coefficient_functional_equality"]
    if functional_assertions:
        if code_uses_signed_small_int(code_summary, artifact_text) and code_has_coeff_addition(code_summary, artifact_text):
            issues.append(
                issue(
                    "medium",
                    "signed_overflow_risk_in_functional_assertion",
                    "The coefficient equality assertion may involve signed small-integer addition, so CBMC may report signed overflow unless valid input bounds are justified.",
                    "Separate memory-safety checking from arithmetic correctness, or add carefully justified coefficient preconditions before checking equality.",
                    functional_assertions[0].get("evidence"),
                    selected_ids,
                )
            )
        if "functional" not in " ".join(selected_types).lower() and "functional" not in json.dumps(selected, ensure_ascii=False).lower():
            issues.append(
                issue(
                    "low",
                    "assertion_not_clearly_selected_property",
                    "The harness contains a functional equality assertion, but the selected manifest properties appear mostly safety-focused.",
                    "Confirm whether functional correctness is intentionally selected for this run or move it into a separate experiment variant.",
                    functional_assertions[0].get("evidence"),
                )
            )

    # 8. CBMC command/check compatibility.
    recommended_flags = ["--bounds-check", "--pointer-check", "--unwinding-assertions"]
    missing_flags = [flag for flag in recommended_flags if flag not in manifest_cmd]
    if missing_flags:
        issues.append(
            issue(
                "medium",
                "missing_recommended_cbmc_flags",
                f"The recommended CBMC command/manifest does not visibly include: {', '.join(missing_flags)}.",
                "Add these checks unless the run intentionally excludes them and documents why.",
            )
        )
    else:
        positives.append("Recommended CBMC command includes bounds, pointer, and unwinding checks.")

    if loops:
        has_unwind = "--unwind" in manifest_cmd or any("unwind" in str(p).lower() for p in selected)
        add_check("loop_unwind_planned", has_unwind, "Loop unwind appears planned" if has_unwind else "Loop unwind not clearly planned", "medium")
        if not has_unwind:
            issues.append(
                issue(
                    "medium",
                    "missing_unwind_plan",
                    "The harness contains loop(s), but no clear CBMC unwind plan was found.",
                    "Use --unwind with --unwinding-assertions and document the selected bound.",
                    loops[0].get("evidence"),
                )
            )
        else:
            positives.append("Loop unwinding is planned through CBMC command/properties.")

    # 9. Nondeterministic input sanity.
    input_params = as_list(code_summary.get("inputs"))
    if input_params and not nondet_uses:
        issues.append(
            issue(
                "medium",
                "missing_nondeterministic_inputs",
                "The selected function has likely input parameters, but the harness does not use visible nondeterministic input generation.",
                "Initialize relevant input fields with nondeterministic values so CBMC explores more than one fixed test case.",
            )
        )
    elif nondet_uses:
        positives.append(f"Harness uses nondeterministic input function(s): {', '.join(sorted({u['function'] for u in nondet_uses}))}.")

    # 10. Array/bounds structural checks.
    selected_has_bounds = any(t in {"array_bounds", "memory_safety", "loop_bound"} for t in selected_types)
    if selected_has_bounds and not array_accesses and not loops:
        issues.append(
            issue(
                "medium",
                "safety_property_without_visible_accesses",
                "Safety/bounds properties are selected, but the harness has no visible array accesses or loops.",
                "Confirm the target call is enough for CBMC to check the implementation, and include source files in the CBMC command.",
            )
        )
    elif array_accesses:
        positives.append(f"Harness contains {len(array_accesses)} visible array access(es), useful for initialization/assertion review.")

    # 11. Constant consistency.
    if spec_n is not None:
        n_text = str(spec_n)
        uses_n_literal_or_symbol = n_text in artifact_text or re.search(r"\b(KYBER_N|MLKEM_N|MLK_N|N)\b", artifact_text)
        add_check(
            "polynomial_size_constant_used",
            bool(uses_n_literal_or_symbol),
            f"Spec N={spec_n}; harness appears to use N/KYBER_N/literal" if uses_n_literal_or_symbol else f"Spec N={spec_n}; harness does not visibly use compatible size constant",
            "medium",
        )
        if not uses_n_literal_or_symbol:
            issues.append(
                issue(
                    "medium",
                    "missing_polynomial_size_constant",
                    f"The spec summary contains N = {spec_n}, but the harness does not visibly use that bound or a known N macro.",
                    "Use the implementation's verified polynomial-size macro or an explicitly justified constant.",
                )
            )
        else:
            positives.append(f"Harness appears to use a polynomial-size bound compatible with spec N={spec_n}.")

    if spec_q is not None and coefficient_bound_assumptions:
        # Warn when q is copied as a numeric bound without more proof context.
        for a in coefficient_bound_assumptions:
            if str(spec_q) in a.get("expression", "") and not has_explicit_spec_bound:
                issues.append(
                    issue(
                        "medium",
                        "q_used_as_input_bound_without_context",
                        f"The assumption `{a['expression']}` appears to reuse q={spec_q} as an input bound, but modulus value alone may not define valid implementation input range.",
                        "Document exactly why q implies this precondition, or avoid using q as an automatic input bound.",
                        a.get("evidence"),
                    )
                )

    # 12. Alias awareness.
    output_params = as_list(code_summary.get("outputs_or_inouts"))
    if output_params and len(input_params) >= 1:
        alias_text = lower_artifact
        mentions_alias = any(word in alias_text for word in ["alias", "separation", "same object", "distinct"])
        if not mentions_alias:
            issues.append(
                issue(
                    "low",
                    "aliasing_not_discussed",
                    "The function has pointer inputs/outputs, but the harness/review material does not discuss aliasing.",
                    "Decide whether aliases like r == a or r == b are allowed by the implementation contract, and document the choice.",
                )
            )
        else:
            positives.append("Artifact text mentions aliasing/separation concerns.")

    # 13. Property coverage.
    property_coverage: List[Dict[str, Any]] = []
    for p in selected:
        p_id = str(p.get("id", "unknown"))
        p_type = str(p.get("type", "unknown"))
        p_text = json.dumps(p, ensure_ascii=False).lower()
        covered_by = []
        if p_type in {"array_bounds", "memory_safety", "pointer_validity", "input_pointer_validity", "output_pointer_validity"}:
            if any(flag in manifest_cmd for flag in ["--bounds-check", "--pointer-check"]):
                covered_by.append("cbmc_builtin_checks")
        if p_type in {"loop_bound", "array_bounds"} and "--unwind" in manifest_cmd:
            covered_by.append("unwind_plan")
        if "functional" in p_type or "equals" in p_text or "output coefficient" in p_text:
            if functional_assertions:
                covered_by.append("explicit_functional_assertion")
        property_coverage.append(
            {
                "property_id": p_id,
                "property_type": p_type,
                "coverage_status": "covered_candidate" if covered_by else "not_clearly_covered",
                "covered_by": covered_by,
            }
        )

    uncovered_high_priority = [
        c for c, p in zip(property_coverage, selected)
        if c["coverage_status"] == "not_clearly_covered" and str(p.get("priority", "")).lower() == "high"
    ]
    if uncovered_high_priority:
        issues.append(
            issue(
                "medium",
                "selected_property_not_clearly_covered",
                f"{len(uncovered_high_priority)} high-priority selected propertie(s) are not clearly covered by assertions or CBMC flags.",
                "Either add explicit assertions/checks or update the property selection for this artifact.",
                related_property_ids=[str(c["property_id"]) for c in uncovered_high_priority],
            )
        )
    elif property_coverage:
        positives.append("Selected properties have at least candidate coverage through CBMC flags or explicit assertions.")

    # 14. Manifest/artifact consistency.
    manifest_artifact_file = str(manifest.get("artifact_file", ""))
    if manifest_artifact_file and Path(manifest_artifact_file).name != artifact_path.name:
        issues.append(
            issue(
                "low",
                "manifest_artifact_filename_mismatch",
                f"Manifest artifact_file points to `{manifest_artifact_file}`, but this review inspected `{artifact_path}`.",
                "Confirm whether the current artifact was repaired/promoted and update the manifest/resolved config if needed.",
            )
        )

    # 15. Unsupported broad claims.
    broad_claim_patterns = [
        r"fully\s+prove[sd]?\s+ml-?kem",
        r"complete\s+proof\s+of\s+ml-?kem",
        r"formally\s+verified\s+entire",
        r"ai\s+proved",
    ]
    for pat in broad_claim_patterns:
        for line_no, line, _ in find_lines_matching(artifact_text, pat, flags=re.I):
            issues.append(
                issue(
                    "high",
                    "unsafe_overclaim_in_artifact_text",
                    "The artifact text appears to contain an unsafe proof overclaim.",
                    "Rewrite the comment/output to say this is only a candidate artifact checked under selected assumptions.",
                    evidence_for_line(artifact_path, line_no, line),
                )
            )

    # Deduplicate issues by type+message+line.
    seen = set()
    deduped: List[Dict[str, Any]] = []
    for it in issues:
        ev = it.get("evidence", {}) if isinstance(it.get("evidence"), dict) else {}
        key = (it.get("severity"), it.get("type"), it.get("message"), ev.get("start_line"))
        if key not in seen:
            seen.add(key)
            deduped.append(it)
    issues = deduped

    return {
        "target_function": target_function,
        "harness_function": harness_function,
        "selected_property_types": selected_types,
        "selected_property_ids": selected_ids,
        "assumptions": assumptions,
        "assertions": assertions,
        "includes": includes,
        "loops": loops,
        "array_accesses": array_accesses,
        "nondet_uses": nondet_uses,
        "function_calls": calls,
        "target_calls": target_calls,
        "property_coverage": property_coverage,
        "issues": issues,
        "positive_findings": positives,
        "checklist": checklist,
        "manifest_command_seen": manifest_cmd,
        "spec_constants_seen": {"N": spec_n, "q": spec_q},
        "iteration": iteration,
    }


# ---------------------------------------------------------------------------
# Prompt and markdown rendering
# ---------------------------------------------------------------------------


def build_prompt_record(
    config: Dict[str, Any],
    spec_summary: Dict[str, Any],
    code_summary: Dict[str, Any],
    properties: Dict[str, Any],
    manifest: Dict[str, Any],
    artifact_text: str,
    artifact_path: Path,
) -> str:
    target = get_target_function(config, code_summary, manifest)
    harness = get_harness_function(config, manifest, target)
    selected = selected_properties(properties, manifest)
    selected_short = [
        {
            "id": p.get("id"),
            "type": p.get("type"),
            "priority": p.get("priority"),
            "description": p.get("description"),
        }
        for p in selected[:20]
    ]
    return f"""You are the Review / Critic Agent for an AI-assisted formal-verification artifact workflow.

Task:
1. Review the generated CBMC harness.
2. Check whether assumptions are too strong or too weak.
3. Check whether assertions are meaningful and connected to selected properties.
4. Check whether the harness calls the correct target function.
5. Check whether constants/input ranges are justified by the selected spec/code summaries.
6. Check whether the artifact might prove something trivial or unsupported.
7. Produce severity-labelled issues and recommended fixes.
8. Do not claim the artifact is a proof.

Target function: {target}
Harness function: {harness}
Artifact path: {artifact_path}

Selected properties summary:
{json.dumps(selected_short, indent=2, ensure_ascii=False)}

Spec constants:
{json.dumps(get_spec_constants(spec_summary), indent=2, ensure_ascii=False)[:4000]}

Code function summary:
{json.dumps(code_summary.get('function', {}), indent=2, ensure_ascii=False)[:4000]}

Artifact preview:
```c
{artifact_text[:8000]}
```

Return a structured JSON review. This file records the deterministic critic task even when no external LLM is used.
"""


def render_markdown(review: Dict[str, Any]) -> str:
    score = review.get("quality_metrics", {})
    lines: List[str] = []
    lines.append("# 05 Critic Review")
    lines.append("")
    lines.append(f"**Agent:** `{AGENT_NAME}`")
    lines.append(f"**Review status:** `{review.get('review_status')}`")
    lines.append(f"**Target function:** `{review.get('target_function')}`")
    lines.append(f"**Harness function:** `{review.get('harness_function')}`")
    lines.append(f"**Artifact:** `{review.get('artifact')}`")
    lines.append(f"**Iteration:** `{review.get('iteration')}`")
    lines.append("")
    lines.append("## Scientific guardrail")
    lines.append("")
    lines.append("This review does not prove the artifact correct. It only checks whether the candidate artifact is reasonable enough to send to the formal tool or whether repair is needed first. CBMC and human review remain the authority.")
    lines.append("")
    lines.append("## Quality metrics")
    lines.append("")
    lines.append(f"- Risk score: `{score.get('risk_score_0_to_100')}` / 100")
    lines.append(f"- Quality score: `{score.get('quality_score_0_to_100')}` / 100")
    lines.append(f"- Highest severity: `{score.get('highest_severity')}`")
    lines.append(f"- Issue count: `{score.get('issue_count')}`")
    lines.append("")
    lines.append("## Decision")
    lines.append("")
    lines.append(f"- Tool execution allowed: `{review.get('tool_execution_allowed')}`")
    lines.append(f"- Repair recommended before tool: `{review.get('repair_recommended_before_tool')}`")
    lines.append(f"- Human review required: `{review.get('human_review_required')}`")
    lines.append("")

    lines.append("## Issues")
    lines.append("")
    issues = as_list(review.get("issues"))
    if not issues:
        lines.append("No blocking issues detected by the deterministic critic. Human review is still required.")
    else:
        for i, it in enumerate(issues, start=1):
            lines.append(f"### {i}. `{it.get('severity')}` — `{it.get('type')}`")
            lines.append("")
            lines.append(str(it.get("message", "")))
            lines.append("")
            lines.append(f"**Recommended fix:** {it.get('recommendation', '')}")
            ev = it.get("evidence")
            if isinstance(ev, dict) and ev.get("text"):
                lines.append("")
                lines.append(f"Evidence line {ev.get('start_line')}: `{ev.get('text')}`")
            lines.append("")

    lines.append("## Positive findings")
    lines.append("")
    positives = as_list(review.get("positive_findings"))
    if positives:
        for item in positives:
            lines.append(f"- {item}")
    else:
        lines.append("- No positive findings recorded.")
    lines.append("")

    lines.append("## Checklist")
    lines.append("")
    checklist = as_list(review.get("review_checklist"))
    if checklist:
        lines.append("| Check | Passed | Details |")
        lines.append("|---|---:|---|")
        for c in checklist:
            passed = "yes" if c.get("passed") else "no"
            details = str(c.get("details", "")).replace("|", "\\|")
            lines.append(f"| `{c.get('check')}` | {passed} | {details} |")
    else:
        lines.append("No checklist items recorded.")
    lines.append("")

    lines.append("## Property coverage")
    lines.append("")
    coverage = as_list(review.get("property_coverage"))
    if coverage:
        lines.append("| Property | Type | Coverage | Covered by |")
        lines.append("|---|---|---|---|")
        for c in coverage:
            covered_by = ", ".join(as_list(c.get("covered_by")))
            lines.append(f"| `{c.get('property_id')}` | `{c.get('property_type')}` | `{c.get('coverage_status')}` | {covered_by} |")
    else:
        lines.append("No selected property coverage map available.")
    lines.append("")

    lines.append("## Next recommended action")
    lines.append("")
    lines.append(str(review.get("next_recommended_action", "Human review required.")))
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main agent
# ---------------------------------------------------------------------------


def determine_artifact_path(run_dir: Path, project_root: Path, config: Dict[str, Any], args: argparse.Namespace) -> Path:
    # Priority: command-line --artifact, status current_artifact, config current_artifact, default.
    if args.artifact:
        p = Path(args.artifact).expanduser()
        if not p.is_absolute():
            # If just a filename, it usually lives in run_dir; otherwise project root.
            p = run_dir / p if len(p.parts) == 1 else project_root / p
        return p.resolve()

    status = read_json(run_dir / "status.json", default={})
    current = status.get("current_artifact") or config.get("current_artifact")
    if current:
        p = Path(str(current)).expanduser()
        if not p.is_absolute():
            p = run_dir / p if len(p.parts) == 1 else project_root / p
        return p.resolve()

    return (run_dir / DEFAULT_ARTIFACT).resolve()


def maybe_find_manifest(run_dir: Path, artifact_path: Path) -> Path:
    # For now Agent 5 writes 04_artifact_manifest.json. Later repaired artifacts may still use it.
    candidates = [
        run_dir / "04_artifact_manifest.json",
        run_dir / "04_generated_artifact_notes.json",
        artifact_path.with_suffix(".manifest.json"),
    ]
    for p in candidates:
        if p.exists():
            return p
    return run_dir / "04_artifact_manifest.json"


def run_agent(args: argparse.Namespace) -> int:
    started_at = utc_now()
    config_path = Path(args.config).expanduser().resolve()
    project_root = find_project_root(config_path)
    config = read_json(config_path)

    run_dir = Path(args.run_dir).expanduser() if args.run_dir else None
    if run_dir is None:
        run_id = str(config.get("run_id") or "run_001")
        run_dir = project_root / "runs" / run_id
    elif not run_dir.is_absolute():
        run_dir = project_root / run_dir
    run_dir = run_dir.resolve()
    run_dir.mkdir(parents=True, exist_ok=True)

    events_path = run_dir / "events.jsonl"
    append_jsonl(
        events_path,
        {
            "time": started_at,
            "agent": AGENT_NAME,
            "event_type": "started",
            "run_dir": str(run_dir),
            "config": str(config_path),
            "iteration": args.iteration,
        },
    )

    spec_path = run_dir / "01_spec_summary.json"
    code_path = run_dir / "02_code_summary.json"
    props_path = run_dir / "03_candidate_properties.json"

    artifact_path = determine_artifact_path(run_dir, project_root, config, args)
    manifest_path = maybe_find_manifest(run_dir, artifact_path)

    spec_summary = read_json(spec_path, default={})
    code_summary = read_json(code_path, default={})
    properties = read_json(props_path, default={})
    manifest = read_json(manifest_path, default={})
    artifact_text = read_text_if_exists(artifact_path)

    prompt_text = build_prompt_record(config, spec_summary, code_summary, properties, manifest, artifact_text, artifact_path)
    prompt_path = run_dir / "llm_prompts" / "05_critic_review_prompt.txt"
    write_text(prompt_path, prompt_text)

    extracted = run_critic_rules(
        artifact_path=artifact_path,
        artifact_text=artifact_text,
        config=config,
        spec_summary=spec_summary,
        code_summary=code_summary,
        properties=properties,
        manifest=manifest,
        iteration=args.iteration,
    )

    issues = as_list(extracted.get("issues"))
    artifact_exists = artifact_path.exists() and bool(artifact_text.strip())
    review_status = review_status_from_issues(issues, artifact_exists)
    quality_metrics = score_from_issues(issues)

    blocking = any(str(i.get("severity", "")).lower() in {"critical", "high"} for i in issues)
    tool_allowed = artifact_exists and not blocking
    repair_before_tool = artifact_exists and blocking

    if not artifact_exists:
        next_action = "Re-run Formal Artifact Generation Agent before attempting CBMC."
    elif repair_before_tool:
        next_action = "Send the artifact to Repair / Refinement Agent before CBMC because high/critical critic issues were found."
    elif review_status == "conditional_accept_for_tool":
        next_action = "Artifact may go to Formal Tool Execution Agent, but preserve critic warnings for counterexample analysis and human review."
    else:
        next_action = "Artifact may go to Formal Tool Execution Agent; human review is still required."

    review: Dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "agent": AGENT_NAME,
        "created_at": utc_now(),
        "started_at": started_at,
        "finished_at": utc_now(),
        "iteration": args.iteration,
        "review_status": review_status,
        "status": review_status,
        "artifact": str(artifact_path),
        "artifact_sha256_16": sha256_short(artifact_text) if artifact_text else None,
        "artifact_exists": artifact_exists,
        "artifact_manifest": str(manifest_path),
        "input_files": {
            "config": str(config_path),
            "spec_summary": str(spec_path),
            "code_summary": str(code_path),
            "candidate_properties": str(props_path),
            "artifact_manifest": str(manifest_path),
            "artifact": str(artifact_path),
        },
        "target_function": extracted.get("target_function"),
        "harness_function": extracted.get("harness_function"),
        "selected_property_types": extracted.get("selected_property_types", []),
        "selected_property_ids": extracted.get("selected_property_ids", []),
        "review_checklist": extracted.get("checklist", []),
        "issues": issues,
        "recommended_fix": [i.get("recommendation") for i in issues if i.get("recommendation")],
        "positive_findings": extracted.get("positive_findings", []),
        "quality_metrics": quality_metrics,
        "tool_execution_allowed": tool_allowed,
        "repair_recommended_before_tool": repair_before_tool,
        "human_review_required": True,
        "next_recommended_action": next_action,
        "assumption_review": {
            "count": len(as_list(extracted.get("assumptions"))),
            "assumptions": extracted.get("assumptions", []),
        },
        "assertion_review": {
            "count": len(as_list(extracted.get("assertions"))),
            "assertions": extracted.get("assertions", []),
        },
        "cbmc_readiness": {
            "manifest_command_seen": extracted.get("manifest_command_seen", ""),
            "target_call_count": len(as_list(extracted.get("target_calls"))),
            "loop_count": len(as_list(extracted.get("loops"))),
            "array_access_count": len(as_list(extracted.get("array_accesses"))),
            "nondet_input_count": len(as_list(extracted.get("nondet_uses"))),
            "spec_constants_seen": extracted.get("spec_constants_seen", {}),
        },
        "property_coverage": extracted.get("property_coverage", []),
        "scientific_guardrail": {
            "claim": "This review does not prove correctness; it only reviews candidate artifact quality before CBMC and human inspection.",
            "llm_or_deterministic": "deterministic_static_review",
            "formal_tool_and_human_are_authority": True,
        },
    }

    review_path = run_dir / "05_critic_review.json"
    md_path = run_dir / "05_critic_review.md"
    status_path = run_dir / "agent_status" / "05_critic_review_status.json"

    write_json(review_path, review)
    write_text(md_path, render_markdown(review))
    write_json(
        status_path,
        {
            "agent": AGENT_NAME,
            "status": "passed" if artifact_exists else "failed",
            "review_status": review_status,
            "tool_execution_allowed": tool_allowed,
            "repair_recommended_before_tool": repair_before_tool,
            "started_at": started_at,
            "finished_at": review["finished_at"],
            "outputs": {
                "review_json": str(review_path),
                "review_markdown": str(md_path),
                "prompt": str(prompt_path),
            },
            "human_review_required": True,
        },
    )

    append_jsonl(
        events_path,
        {
            "time": utc_now(),
            "agent": AGENT_NAME,
            "event_type": "finished",
            "status": "ok" if artifact_exists else "failed",
            "review_status": review_status,
            "iteration": args.iteration,
            "issue_count": len(issues),
            "highest_severity": quality_metrics.get("highest_severity"),
            "tool_execution_allowed": tool_allowed,
            "outputs": {
                "review_json": str(review_path),
                "review_markdown": str(md_path),
                "prompt": str(prompt_path),
            },
        },
    )

    print(f"[OK] Review / Critic Agent wrote: {review_path}")
    print(f"[OK] Markdown review: {md_path}")
    print(f"[INFO] Review status: {review_status}")
    print(f"[INFO] Issues: {len(issues)} | Highest severity: {quality_metrics.get('highest_severity')}")
    print(f"[INFO] Tool execution allowed: {tool_allowed}")
    print("[NOTE] This is a critic review only; CBMC and human review remain the authority.")

    # Do not return nonzero for needs_revision: the Master Orchestrator decides repair from JSON.
    return 0 if artifact_exists else 2


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Agent 6: Review / Critic Agent")
    parser.add_argument("--config", required=True, help="Path to run config JSON, e.g., configs/poly_add_run.json")
    parser.add_argument("--run-dir", required=False, help="Run directory, e.g., runs/run_001_poly_add")
    parser.add_argument("--iteration", type=int, default=0, help="Refinement iteration number")
    parser.add_argument("--artifact", required=False, help="Optional artifact filename/path to review, e.g., 04_generated_harness.c")
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)
    try:
        return run_agent(args)
    except Exception as exc:
        print(f"[ERROR] Review / Critic Agent failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
