#!/usr/bin/env python3
"""
Formal Tool Execution Agent (Agent 7)
=====================================

Purpose
-------
Runs the selected formal verification tool, currently CBMC, on the candidate
formal-verification artifact generated by Agent 5 and reviewed by Agent 6.

This agent is intentionally careful:
- It treats generated harnesses as candidate artifacts only.
- It does not interpret a CBMC pass as "full ML-KEM is proved".
- It saves every command, output, status, and warning for reproducibility.
- A CBMC verification failure is a research result, not a Python crash.

Expected inputs in run directory
--------------------------------
- 04_generated_harness.c or 08_repaired_harness.c
- 04_artifact_manifest.json, if available
- 05_critic_review.json, if available
- run_config.resolved.json, if available
- original config JSON

Expected outputs in run directory
---------------------------------
- 06_cbmc_output.txt
- 06_cbmc_status.json
- 06_cbmc_command.txt
- 06_tool_execution.md
- 06_cbmc_property_results.json
- agent_status/06_tool_execution_status.json
- tool_outputs/cbmc_output_iteration_<N>.txt

CLI example
-----------
python3 agents/tool_execution_agent.py \
  --config configs/poly_add_run.json \
  --run-dir runs/run_001_poly_add \
  --iteration 0 \
  --artifact 04_generated_harness.c
"""

from __future__ import annotations

import argparse
import dataclasses
import datetime as _dt
import hashlib
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import textwrap
import time
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

JsonDict = Dict[str, Any]


# ---------------------------------------------------------------------------
# Small file/helpers layer
# ---------------------------------------------------------------------------


def utc_now() -> str:
    return _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds")


def read_text(path: Path, default: str = "") -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except FileNotFoundError:
        return default


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def read_json(path: Path, default: Optional[JsonDict] = None) -> JsonDict:
    if default is None:
        default = {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return dict(default)
    except json.JSONDecodeError:
        return dict(default)


def write_json(path: Path, data: JsonDict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def append_jsonl(path: Path, event: JsonDict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(event, ensure_ascii=False) + "\n")


def sha256_file(path: Path) -> Optional[str]:
    if not path.exists() or not path.is_file():
        return None
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def unique_preserve_order(items: Iterable[Any]) -> List[Any]:
    seen = set()
    out = []
    for item in items:
        key = str(item)
        if key in seen:
            continue
        seen.add(key)
        out.append(item)
    return out


def as_bool(value: Any, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return default
    if isinstance(value, (int, float)):
        return bool(value)
    text = str(value).strip().lower()
    if text in {"1", "true", "yes", "y", "on"}:
        return True
    if text in {"0", "false", "no", "n", "off"}:
        return False
    return default


# ---------------------------------------------------------------------------
# CBMC parsing data structures
# ---------------------------------------------------------------------------


@dataclasses.dataclass
class PropertyResult:
    raw_line: str
    property_id: Optional[str]
    description: str
    status: str
    property_type: Optional[str] = None


@dataclasses.dataclass
class ParsedToolOutput:
    status: str
    verification_passed: bool
    counterexample_available: bool
    failed_property: Optional[str]
    failed_properties_count: int
    successful_properties_count: int
    property_results: List[PropertyResult]
    detected_errors: List[str]
    warnings: List[str]
    summary: str


@dataclasses.dataclass
class ExecutionResult:
    status_json: JsonDict
    raw_output: str
    markdown: str


# ---------------------------------------------------------------------------
# Main agent
# ---------------------------------------------------------------------------


class ToolExecutionAgent:
    """Runs CBMC and stores a reproducible formal-tool result."""

    CHECK_FLAG_MAP: Dict[str, str] = {
        "bounds_check": "--bounds-check",
        "pointer_check": "--pointer-check",
        "memory_leak_check": "--memory-leak-check",
        "signed_overflow_check": "--signed-overflow-check",
        "unsigned_overflow_check": "--unsigned-overflow-check",
        "div_by_zero_check": "--div-by-zero-check",
        "undefined_shift_check": "--undefined-shift-check",
        "conversion_check": "--conversion-check",
        "float_overflow_check": "--float-overflow-check",
        "nan_check": "--nan-check",
    }

    DEFAULT_CBMC_FLAGS: Dict[str, bool] = {
        "bounds_check": True,
        "pointer_check": True,
        "signed_overflow_check": True,
        "unsigned_overflow_check": True,
        "unwinding_assertions": True,
        "trace": True,
    }

    def __init__(
        self,
        config_path: Path,
        run_dir: Optional[Path] = None,
        iteration: int = 0,
        artifact: Optional[str] = None,
        dry_run: bool = False,
        force: bool = False,
        timeout_seconds: Optional[int] = None,
    ) -> None:
        self.config_path = config_path.resolve()
        self.project_root = self.infer_project_root(self.config_path)
        self.config = read_json(self.config_path)

        # If the orchestrator wrote a resolved config, prefer it because it includes
        # current_artifact after repair promotion and resolved run information.
        initial_run_dir = self.resolve_run_dir(run_dir)
        resolved_config_path = initial_run_dir / "run_config.resolved.json"
        self.resolved_config = read_json(resolved_config_path, default={})
        if self.resolved_config:
            merged = dict(self.config)
            merged.update(self.resolved_config)
            self.config = merged

        self.run_dir = self.resolve_run_dir(run_dir)
        self.iteration = int(iteration)
        self.artifact_arg = artifact or self.config.get("current_artifact") or "04_generated_harness.c"
        self.dry_run = dry_run
        self.force = force
        self.timeout_seconds = timeout_seconds

        self.output_path = self.run_dir / "06_cbmc_output.txt"
        self.status_path = self.run_dir / "06_cbmc_status.json"
        self.command_path = self.run_dir / "06_cbmc_command.txt"
        self.md_path = self.run_dir / "06_tool_execution.md"
        self.property_results_path = self.run_dir / "06_cbmc_property_results.json"
        self.agent_status_path = self.run_dir / "agent_status" / "06_tool_execution_status.json"
        self.events_path = self.run_dir / "events.jsonl"
        self.tool_outputs_dir = self.run_dir / "tool_outputs"
        self.prompts_dir = self.run_dir / "llm_prompts"

        self.manifest = self.load_manifest()
        self.critic_review = read_json(self.run_dir / "05_critic_review.json", default={})
        self.properties = read_json(self.run_dir / "03_candidate_properties.json", default={})
        self.code_summary = read_json(self.run_dir / "02_code_summary.json", default={})

    # ------------------------------------------------------------------
    # Path/config resolution
    # ------------------------------------------------------------------

    @staticmethod
    def infer_project_root(config_path: Path) -> Path:
        # Common layout: thesis-agent-workflow/configs/poly_add_run.json
        if config_path.parent.name == "configs":
            return config_path.parent.parent.resolve()
        return Path.cwd().resolve()

    def resolve_project_path(self, maybe_path: Any) -> Path:
        p = Path(str(maybe_path))
        if p.is_absolute():
            return p
        return (self.project_root / p).resolve()

    def resolve_run_dir(self, run_dir: Optional[Path]) -> Path:
        if run_dir is not None:
            p = Path(run_dir)
            if p.is_absolute():
                return p.resolve()
            return (self.project_root / p).resolve()

        configured_root = self.config.get("output_root", "runs")
        run_id = self.config.get("run_id") or "run_001"
        return (self.project_root / str(configured_root) / str(run_id)).resolve()

    def resolve_artifact_path(self) -> Path:
        p = Path(str(self.artifact_arg))
        if p.is_absolute():
            return p.resolve()
        candidate_in_run = (self.run_dir / p).resolve()
        if candidate_in_run.exists():
            return candidate_in_run
        candidate_in_project = (self.project_root / p).resolve()
        if candidate_in_project.exists():
            return candidate_in_project
        # Prefer run directory even when missing, because generated/repaired artifacts
        # are promised to live there.
        return candidate_in_run

    def load_manifest(self) -> JsonDict:
        candidate_paths = [
            self.run_dir / "04_artifact_manifest.json",
            self.run_dir / "04_generated_artifact_notes.json",
            self.run_dir / "artifact_manifest.json",
        ]
        for p in candidate_paths:
            data = read_json(p, default={})
            if data:
                data["_manifest_path"] = str(p)
                return data
        return {}

    def log_event(self, event_type: str, payload: JsonDict) -> None:
        append_jsonl(
            self.events_path,
            {
                "ts": utc_now(),
                "agent": "tool_execution_agent",
                "event": event_type,
                **payload,
            },
        )

    # ------------------------------------------------------------------
    # Command construction
    # ------------------------------------------------------------------

    def cbmc_settings(self) -> JsonDict:
        base: JsonDict = {}
        if isinstance(self.config.get("cbmc_settings"), dict):
            base.update(self.config.get("cbmc_settings") or {})
        if isinstance(self.config.get("tool_execution_settings"), dict):
            tes = self.config.get("tool_execution_settings") or {}
            # Allow either nested cbmc_settings or direct values.
            if isinstance(tes.get("cbmc_settings"), dict):
                base.update(tes.get("cbmc_settings") or {})
            for key in [
                "cbmc_binary",
                "function",
                "unwind",
                "object_bits",
                "bounds_check",
                "pointer_check",
                "signed_overflow_check",
                "unsigned_overflow_check",
                "unwinding_assertions",
                "trace",
                "extra_args",
                "timeout_seconds",
                "execute",
            ]:
                if key in tes:
                    base[key] = tes[key]
        return base

    def infer_harness_function(self, artifact_text: str, artifact_path: Path) -> str:
        cbmc = self.cbmc_settings()
        configured = cbmc.get("function") or self.manifest.get("harness_function")
        if configured:
            return str(configured)

        # Prefer explicit harness_* function names.
        patterns = [
            r"\bvoid\s+(harness_[A-Za-z_][A-Za-z0-9_]*)\s*\(",
            r"\bint\s+(harness_[A-Za-z_][A-Za-z0-9_]*)\s*\(",
            r"\bvoid\s+([A-Za-z_][A-Za-z0-9_]*harness[A-Za-z0-9_]*)\s*\(",
            r"\bint\s+([A-Za-z_][A-Za-z0-9_]*harness[A-Za-z0-9_]*)\s*\(",
        ]
        for pat in patterns:
            m = re.search(pat, artifact_text)
            if m:
                return m.group(1)

        target = str(self.config.get("target_function") or self.manifest.get("target_function") or "target")
        return f"harness_{target}"

    def source_files_from_config_and_manifest(self, artifact_path: Path) -> List[Path]:
        files: List[Path] = []

        # Manifest source files are usually produced by Agent 5.
        input_files = self.manifest.get("input_files") if isinstance(self.manifest.get("input_files"), dict) else {}
        for key in ["source_files", "code_files"]:
            values = input_files.get(key) or []
            if isinstance(values, str):
                values = [values]
            for v in values:
                p = Path(str(v))
                if not p.is_absolute():
                    # Manifest may store absolute paths; if not, resolve relative to project first.
                    p = self.resolve_project_path(v)
                if p.resolve() != artifact_path.resolve():
                    files.append(p.resolve())

        # Config source_file and optional extra source_files.
        for key in ["source_file", "source_files"]:
            values = self.config.get(key)
            if not values:
                continue
            if isinstance(values, str):
                values = [values]
            if isinstance(values, list):
                for v in values:
                    p = self.resolve_project_path(v)
                    if p.resolve() != artifact_path.resolve():
                        files.append(p)

        tes = self.config.get("tool_execution_settings") if isinstance(self.config.get("tool_execution_settings"), dict) else {}
        extra_sources = tes.get("extra_source_files") or tes.get("source_files") or []
        if isinstance(extra_sources, str):
            extra_sources = [extra_sources]
        for v in extra_sources:
            p = self.resolve_project_path(v)
            if p.resolve() != artifact_path.resolve():
                files.append(p)

        return unique_preserve_order(files)

    def header_include_dirs(self) -> List[Path]:
        dirs: List[Path] = []
        header_values = self.config.get("header_files") or []
        if isinstance(header_values, str):
            header_values = [header_values]
        for v in header_values:
            p = self.resolve_project_path(v)
            if p.parent.exists():
                dirs.append(p.parent.resolve())

        input_files = self.manifest.get("input_files") if isinstance(self.manifest.get("input_files"), dict) else {}
        header_values = input_files.get("header_files") or []
        if isinstance(header_values, str):
            header_values = [header_values]
        for v in header_values:
            p = Path(str(v))
            if not p.is_absolute():
                p = self.resolve_project_path(v)
            if p.parent.exists():
                dirs.append(p.parent.resolve())

        tes = self.config.get("tool_execution_settings") if isinstance(self.config.get("tool_execution_settings"), dict) else {}
        include_dirs = tes.get("include_dirs") or []
        if isinstance(include_dirs, str):
            include_dirs = [include_dirs]
        for v in include_dirs:
            p = self.resolve_project_path(v)
            if p.exists():
                dirs.append(p.resolve())

        return unique_preserve_order(dirs)

    def build_cbmc_command(self, artifact_path: Path, artifact_text: str) -> Tuple[List[str], JsonDict]:
        cbmc = self.cbmc_settings()
        binary = str(cbmc.get("cbmc_binary") or os.environ.get("CBMC", "cbmc"))
        harness_function = self.infer_harness_function(artifact_text, artifact_path)

        command: List[str] = [binary, str(artifact_path)]

        existing_source_files: List[Path] = []
        missing_source_files: List[Path] = []
        for p in self.source_files_from_config_and_manifest(artifact_path):
            if p.exists():
                existing_source_files.append(p)
                command.append(str(p))
            else:
                missing_source_files.append(p)

        include_dirs = self.header_include_dirs()
        for d in include_dirs:
            command.extend(["-I", str(d)])

        command.extend(["--function", harness_function])

        # Default promised safety checks, overridable from config.
        for setting_name, flag in self.CHECK_FLAG_MAP.items():
            value = cbmc.get(setting_name, self.DEFAULT_CBMC_FLAGS.get(setting_name, False))
            if as_bool(value, default=False):
                command.append(flag)

        unwind = cbmc.get("unwind")
        if unwind is None:
            loop_bound = self.manifest.get("loop_bound_used") or self.properties.get("recommended_unwind")
            if loop_bound:
                unwind = loop_bound
        if unwind is not None and str(unwind).strip() != "":
            command.extend(["--unwind", str(unwind)])

        if as_bool(cbmc.get("unwinding_assertions", self.DEFAULT_CBMC_FLAGS["unwinding_assertions"]), default=True):
            command.append("--unwinding-assertions")

        if as_bool(cbmc.get("trace", self.DEFAULT_CBMC_FLAGS["trace"]), default=True):
            command.append("--trace")

        if cbmc.get("object_bits") is not None:
            command.extend(["--object-bits", str(cbmc["object_bits"])])

        extra_args = cbmc.get("extra_args") or []
        if isinstance(extra_args, str):
            extra_args = shlex.split(extra_args)
        if isinstance(extra_args, list):
            command.extend(str(x) for x in extra_args)

        meta = {
            "cbmc_binary": binary,
            "harness_function": harness_function,
            "existing_source_files": [str(p) for p in existing_source_files],
            "missing_source_files": [str(p) for p in missing_source_files],
            "include_dirs": [str(p) for p in include_dirs],
            "settings_used": cbmc,
        }
        return command, meta

    # ------------------------------------------------------------------
    # Tool output parsing
    # ------------------------------------------------------------------

    @staticmethod
    def classify_property_type(line: str) -> Optional[str]:
        lower = line.lower()
        if "pointer" in lower or "dereference" in lower:
            return "pointer_safety"
        if "array" in lower or "bounds" in lower:
            return "bounds_safety"
        if "overflow" in lower:
            return "integer_overflow"
        if "unwind" in lower:
            return "loop_unwinding"
        if "assert" in lower or "assertion" in lower:
            return "assertion"
        if "memory" in lower:
            return "memory_safety"
        return None

    def parse_tool_output(self, raw_output: str, returncode: Optional[int], timed_out: bool = False) -> ParsedToolOutput:
        text = raw_output or ""
        lines = text.splitlines()
        lower = text.lower()

        property_results: List[PropertyResult] = []
        for line in lines:
            stripped = line.strip()
            # CBMC common result line examples:
            # [foo.pointer_dereference.1] line 10 dereference failure: SUCCESS
            # [harness.assertion.1] assertion x == y: FAILURE
            m = re.match(r"^\[([^\]]+)\]\s*(.*?):\s*(SUCCESS|FAILURE|UNKNOWN)\s*$", stripped, flags=re.IGNORECASE)
            if m:
                property_results.append(
                    PropertyResult(
                        raw_line=stripped,
                        property_id=m.group(1),
                        description=m.group(2).strip(),
                        status=m.group(3).upper(),
                        property_type=self.classify_property_type(stripped),
                    )
                )
                continue

            # Some CBMC versions print "Status: SUCCESS" / "Status: FAILURE".
            m2 = re.match(r"^Status:\s*(SUCCESS|FAILURE|UNKNOWN)\s*$", stripped, flags=re.IGNORECASE)
            if m2:
                property_results.append(
                    PropertyResult(
                        raw_line=stripped,
                        property_id=None,
                        description="CBMC status line",
                        status=m2.group(1).upper(),
                        property_type=None,
                    )
                )

        successful_properties_count = sum(1 for p in property_results if p.status == "SUCCESS")
        failed_properties = [p for p in property_results if p.status == "FAILURE"]
        failed_properties_count = len(failed_properties)
        failed_property = failed_properties[0].property_id if failed_properties else None

        detected_errors: List[str] = []
        warnings: List[str] = []

        error_patterns = [
            r"\bERROR:\s*(.+)",
            r"\bFailed to open\s+(.+)",
            r"\bfile .* not found\b",
            r"\bparse error\b.*",
            r"\bsyntax error\b.*",
            r"\bcompilation failed\b.*",
            r"\bPARSING ERROR\b.*",
            r"\bCONVERSION ERROR\b.*",
        ]
        for line in lines:
            for pat in error_patterns:
                if re.search(pat, line, flags=re.IGNORECASE):
                    detected_errors.append(line.strip())
                    break
            if re.search(r"\bwarning[: ]", line, flags=re.IGNORECASE):
                warnings.append(line.strip())

        # Top-level classification.
        if timed_out:
            status = "timeout"
            verification_passed = False
            summary = "CBMC execution timed out."
        elif "verification successful" in lower:
            status = "passed"
            verification_passed = True
            summary = "CBMC reported VERIFICATION SUCCESSFUL for the selected harness/properties."
        elif "verification failed" in lower or failed_properties_count > 0 or "violated property" in lower:
            status = "failed"
            verification_passed = False
            summary = "CBMC reported a verification failure or at least one failed property."
        elif detected_errors:
            status = "tool_error"
            verification_passed = False
            summary = "CBMC produced parsing/conversion/tool errors before a clean verification result."
        elif returncode not in (0, None):
            # Avoid treating non-zero returncode alone as proof failure unless output says so.
            status = "tool_error_or_failure"
            verification_passed = False
            summary = "CBMC exited with a non-zero return code, but output did not clearly classify pass/fail."
        elif property_results and failed_properties_count == 0:
            status = "passed"
            verification_passed = True
            summary = "CBMC property result lines contain no failures."
        else:
            status = "unknown"
            verification_passed = False
            summary = "CBMC output did not contain a clear verification success/failure marker."

        counterexample_available = bool(
            failed_properties_count > 0
            or "counterexample" in lower
            or "trace for" in lower
            or "violated property" in lower
            or "verification failed" in lower
        )

        return ParsedToolOutput(
            status=status,
            verification_passed=verification_passed,
            counterexample_available=counterexample_available,
            failed_property=failed_property,
            failed_properties_count=failed_properties_count,
            successful_properties_count=successful_properties_count,
            property_results=property_results,
            detected_errors=unique_preserve_order(detected_errors),
            warnings=unique_preserve_order(warnings),
            summary=summary,
        )

    # ------------------------------------------------------------------
    # Execution and output rendering
    # ------------------------------------------------------------------

    def execute_command(self, command: List[str], timeout_seconds: int) -> Tuple[str, Optional[int], bool, Optional[str], float]:
        started = time.monotonic()
        try:
            proc = subprocess.run(
                command,
                cwd=str(self.project_root),
                text=True,
                capture_output=True,
                timeout=timeout_seconds,
                check=False,
            )
            duration = time.monotonic() - started
            combined = ""
            if proc.stdout:
                combined += proc.stdout
            if proc.stderr:
                if combined and not combined.endswith("\n"):
                    combined += "\n"
                combined += "\n--- STDERR ---\n" + proc.stderr
            return combined, proc.returncode, False, None, duration
        except subprocess.TimeoutExpired as e:
            duration = time.monotonic() - started
            combined = ""
            if e.stdout:
                combined += e.stdout if isinstance(e.stdout, str) else e.stdout.decode("utf-8", errors="replace")
            if e.stderr:
                stderr = e.stderr if isinstance(e.stderr, str) else e.stderr.decode("utf-8", errors="replace")
                if combined and not combined.endswith("\n"):
                    combined += "\n"
                combined += "\n--- STDERR ---\n" + stderr
            combined += f"\n\n[TIMEOUT] CBMC command exceeded {timeout_seconds} seconds.\n"
            return combined, None, True, f"Timeout after {timeout_seconds} seconds", duration
        except OSError as e:
            duration = time.monotonic() - started
            return f"[OS ERROR] Could not execute command: {e}\n", None, False, str(e), duration

    def render_markdown(self, status: JsonDict) -> str:
        cmd = status.get("command_shell") or ""
        result = status.get("status")
        counterexample = status.get("counterexample_available")
        failed_property = status.get("failed_property")
        runtime = status.get("runtime_seconds")
        notes = status.get("notes") or []
        warnings = status.get("warnings") or []
        errors = status.get("detected_errors") or []

        lines = [
            "# Agent 7 — Formal Tool Execution Report",
            "",
            f"- **Created at:** {status.get('created_at')}",
            f"- **Tool:** {status.get('tool')}",
            f"- **Target function:** `{status.get('target_function')}`",
            f"- **Harness function:** `{status.get('harness_function')}`",
            f"- **Artifact:** `{status.get('artifact_file')}`",
            f"- **Iteration:** {status.get('iteration')}",
            f"- **Status:** `{result}`",
            f"- **Runtime seconds:** {runtime}",
            f"- **Counterexample available:** {counterexample}",
            "",
            "## Command",
            "",
            "```bash",
            cmd,
            "```",
            "",
            "## Tool Result Summary",
            "",
            status.get("summary") or "No summary available.",
            "",
        ]

        if failed_property:
            lines.extend(["## First Failed Property", "", f"`{failed_property}`", ""])

        if errors:
            lines.extend(["## Detected Tool/Parsing Errors", ""])
            for e in errors[:20]:
                lines.append(f"- {e}")
            lines.append("")

        if warnings:
            lines.extend(["## Warnings", ""])
            for w in warnings[:20]:
                lines.append(f"- {w}")
            lines.append("")

        if notes:
            lines.extend(["## Agent Notes", ""])
            for n in notes:
                lines.append(f"- {n}")
            lines.append("")

        lines.extend(
            [
                "## Scientific Guardrail",
                "",
                "This result applies only to the selected generated/repaired harness and the selected CBMC properties under the recorded assumptions. It must not be reported as full ML-KEM implementation verification.",
                "",
                "## Output Files",
                "",
                "- `06_cbmc_output.txt`",
                "- `06_cbmc_status.json`",
                "- `06_cbmc_command.txt`",
                "- `06_cbmc_property_results.json`",
                "",
            ]
        )
        return "\n".join(lines)

    def render_prompt_record(self, artifact_path: Path, command: List[str]) -> str:
        # Not an LLM prompt in this agent, but we store the execution instruction in the
        # same prompts folder for consistent thesis logging.
        return textwrap.dedent(
            f"""
            Agent 7 Formal Tool Execution Instruction
            ========================================

            Task:
            Run the formal verification tool on the current candidate artifact.

            Tool:
            CBMC

            Artifact:
            {artifact_path}

            Shell command:
            {shlex.join(command)}

            Scientific guardrails:
            - Treat the harness as a candidate formal-verification artifact.
            - Treat CBMC as the formal checker for the selected harness/property only.
            - Do not claim full ML-KEM verification from this run.
            - Save stdout, stderr, command, status, property results, and notes.
            """
        ).strip() + "\n"

    def run(self) -> int:
        self.run_dir.mkdir(parents=True, exist_ok=True)
        self.tool_outputs_dir.mkdir(parents=True, exist_ok=True)
        self.prompts_dir.mkdir(parents=True, exist_ok=True)
        (self.run_dir / "agent_status").mkdir(parents=True, exist_ok=True)

        self.log_event("agent_start", {"iteration": self.iteration, "artifact_arg": str(self.artifact_arg)})

        artifact_path = self.resolve_artifact_path()
        artifact_text = read_text(artifact_path, default="")
        command, command_meta = self.build_cbmc_command(artifact_path, artifact_text)
        command_shell = shlex.join(command)
        cbmc_binary = command_meta["cbmc_binary"]
        cbmc_binary_path = shutil.which(cbmc_binary)
        cbmc = self.cbmc_settings()

        timeout_seconds = int(
            self.timeout_seconds
            or cbmc.get("timeout_seconds")
            or (self.config.get("tool_execution_settings") or {}).get("timeout_seconds", 600)
            if isinstance(self.config.get("tool_execution_settings"), dict)
            else 600
        )
        if timeout_seconds <= 0:
            timeout_seconds = 600

        notes: List[str] = []
        if self.critic_review:
            review_status = self.critic_review.get("review_status") or self.critic_review.get("status")
            notes.append(f"Critic review status before tool execution: {review_status}")
        notes.append("LLM/agent-generated artifacts are candidate artifacts only; CBMC and human review remain required.")

        if command_meta.get("missing_source_files"):
            notes.append("Some configured source files are missing; CBMC may fail unless the harness is self-contained.")

        write_text(self.command_path, command_shell + "\n")
        write_text(self.prompts_dir / "06_tool_execution_instruction.txt", self.render_prompt_record(artifact_path, command))

        created_at = utc_now()
        base_status: JsonDict = {
            "schema_version": "1.0",
            "agent": "tool_execution_agent",
            "created_at": created_at,
            "iteration": self.iteration,
            "target_scheme": self.config.get("target_scheme"),
            "target_function": self.config.get("target_function") or self.manifest.get("target_function"),
            "tool": "CBMC",
            "verification_tool": self.config.get("verification_tool", "CBMC"),
            "artifact_type": self.config.get("artifact_type"),
            "artifact_file": str(artifact_path),
            "artifact_exists": artifact_path.exists(),
            "artifact_sha256": sha256_file(artifact_path),
            "harness_function": command_meta.get("harness_function"),
            "command": command,
            "command_shell": command_shell,
            "command_file": str(self.command_path),
            "cbmc_binary": cbmc_binary,
            "cbmc_binary_path": cbmc_binary_path,
            "cbmc_available": bool(cbmc_binary_path),
            "project_root": str(self.project_root),
            "run_dir": str(self.run_dir),
            "existing_source_files": command_meta.get("existing_source_files", []),
            "missing_source_files": command_meta.get("missing_source_files", []),
            "include_dirs": command_meta.get("include_dirs", []),
            "timeout_seconds": timeout_seconds,
            "notes": notes,
            "scientific_guardrails": {
                "candidate_artifact_only": True,
                "formal_tool_checks_selected_harness_only": True,
                "human_review_required": True,
                "do_not_claim_full_mlkem_proof": True,
                "log_failures_honestly": True,
            },
        }

        raw_output = ""
        returncode: Optional[int] = None
        timed_out = False
        runtime_seconds = 0.0
        execution_error: Optional[str] = None

        execute_enabled = as_bool(cbmc.get("execute", True), default=True)

        if not artifact_path.exists():
            raw_output = f"[TOOL EXECUTION AGENT] Artifact file not found: {artifact_path}\n"
            parsed = self.parse_tool_output(raw_output, returncode=None)
            status = {
                **base_status,
                "execution_status": "artifact_missing",
                "status": "artifact_missing",
                "result": "artifact_missing",
                "verification_passed": False,
                "counterexample_available": False,
                "returncode": None,
                "runtime_seconds": runtime_seconds,
                "summary": raw_output.strip(),
                "failed_property": None,
                "failed_properties_count": 0,
                "successful_properties_count": 0,
                "property_results": [],
                "detected_errors": [raw_output.strip()],
                "warnings": [],
                "next_required_agent": "repair_agent_or_human_fix",
            }
        elif self.dry_run or not execute_enabled:
            raw_output = (
                "[DRY RUN] CBMC was not executed. Command was constructed and logged.\n\n"
                f"Command:\n{command_shell}\n"
            )
            parsed = self.parse_tool_output(raw_output, returncode=None)
            status = {
                **base_status,
                "execution_status": "dry_run_not_executed",
                "status": "dry_run",
                "result": "dry_run",
                "verification_passed": False,
                "counterexample_available": False,
                "returncode": None,
                "runtime_seconds": runtime_seconds,
                "summary": "Dry run only. CBMC command was generated but not executed.",
                "failed_property": None,
                "failed_properties_count": 0,
                "successful_properties_count": 0,
                "property_results": [],
                "detected_errors": [],
                "warnings": parsed.warnings,
                "next_required_agent": "formal_tool_execution_when_ready",
            }
        elif not cbmc_binary_path:
            raw_output = textwrap.dedent(
                f"""
                [TOOL UNAVAILABLE]
                CBMC binary was not found in PATH.

                Requested binary: {cbmc_binary}
                Project root: {self.project_root}

                Command that would have been executed:
                {command_shell}

                This is not a proof failure and not an implementation bug.
                It means the formal tool is not installed or not visible to this shell.
                """
            ).strip() + "\n"
            parsed = self.parse_tool_output(raw_output, returncode=None)
            status = {
                **base_status,
                "execution_status": "tool_unavailable",
                "status": "tool_unavailable",
                "result": "tool_unavailable",
                "verification_passed": False,
                "counterexample_available": False,
                "returncode": None,
                "runtime_seconds": runtime_seconds,
                "summary": "CBMC binary was not found in PATH. The command was logged but not executed.",
                "failed_property": None,
                "failed_properties_count": 0,
                "successful_properties_count": 0,
                "property_results": [],
                "detected_errors": ["CBMC binary not found in PATH"],
                "warnings": parsed.warnings,
                "next_required_agent": "install_or_configure_cbmc_then_rerun",
            }
        else:
            raw_output, returncode, timed_out, execution_error, runtime_seconds = self.execute_command(command, timeout_seconds)
            parsed = self.parse_tool_output(raw_output, returncode=returncode, timed_out=timed_out)
            status = {
                **base_status,
                "execution_status": "executed_timeout" if timed_out else "executed",
                "status": parsed.status,
                "result": parsed.status,
                "verification_passed": parsed.verification_passed,
                "counterexample_available": parsed.counterexample_available,
                "returncode": returncode,
                "runtime_seconds": round(runtime_seconds, 3),
                "summary": parsed.summary,
                "failed_property": parsed.failed_property,
                "failed_properties_count": parsed.failed_properties_count,
                "successful_properties_count": parsed.successful_properties_count,
                "property_results": [dataclasses.asdict(p) for p in parsed.property_results],
                "detected_errors": parsed.detected_errors,
                "warnings": parsed.warnings,
                "execution_error": execution_error,
                "next_required_agent": "evaluation_reporter" if parsed.verification_passed else "counterexample_analysis_agent",
            }

        # Record raw output in both promised root file and iteration-specific folder.
        write_text(self.output_path, raw_output)
        iteration_output = self.tool_outputs_dir / f"cbmc_output_iteration_{self.iteration:02d}.txt"
        write_text(iteration_output, raw_output)
        status["output_file"] = str(self.output_path)
        status["iteration_output_file"] = str(iteration_output)

        property_results_json = {
            "created_at": utc_now(),
            "agent": "tool_execution_agent",
            "iteration": self.iteration,
            "artifact_file": str(artifact_path),
            "property_results": status.get("property_results", []),
            "failed_properties_count": status.get("failed_properties_count", 0),
            "successful_properties_count": status.get("successful_properties_count", 0),
        }
        write_json(self.property_results_path, property_results_json)

        markdown = self.render_markdown(status)
        write_text(self.md_path, markdown)
        write_json(self.status_path, status)
        write_json(
            self.agent_status_path,
            {
                "agent": "tool_execution_agent",
                "status": "completed",
                "tool_status": status.get("status"),
                "created_at": utc_now(),
                "iteration": self.iteration,
                "outputs": {
                    "cbmc_output": str(self.output_path),
                    "cbmc_status": str(self.status_path),
                    "cbmc_command": str(self.command_path),
                    "markdown_report": str(self.md_path),
                    "property_results": str(self.property_results_path),
                },
            },
        )

        self.log_event(
            "agent_finish",
            {
                "iteration": self.iteration,
                "status": status.get("status"),
                "execution_status": status.get("execution_status"),
                "verification_passed": status.get("verification_passed"),
                "counterexample_available": status.get("counterexample_available"),
                "runtime_seconds": status.get("runtime_seconds"),
                "output_file": str(self.output_path),
                "status_file": str(self.status_path),
            },
        )

        # Return 0 even when CBMC reports verification failure, because a formal
        # verification failure is data for the next Counterexample Analysis Agent.
        print(f"[OK] Formal Tool Execution Agent wrote: {self.status_path}")
        print(f"[OK] Raw tool output: {self.output_path}")
        print(f"[STATUS] {status.get('status')}")
        if status.get("status") == "passed":
            print("[NOTE] CBMC passed only the selected candidate harness/properties under recorded assumptions.")
        elif status.get("status") == "tool_unavailable":
            print("[NOTE] CBMC is not installed or not on PATH; command was saved for later execution.")
        else:
            print("[NOTE] Non-pass status is recorded honestly for counterexample analysis / repair.")
        return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Formal Tool Execution Agent for the AI-assisted formal-verification artifact workflow."
    )
    parser.add_argument("--config", required=True, help="Path to run config JSON, e.g., configs/poly_add_run.json")
    parser.add_argument("--run-dir", required=False, help="Run directory, e.g., runs/run_001_poly_add")
    parser.add_argument("--iteration", type=int, default=0, help="Current refinement iteration number")
    parser.add_argument("--artifact", default=None, help="Artifact filename/path to verify, e.g., 04_generated_harness.c or 08_repaired_harness.c")
    parser.add_argument("--dry-run", action="store_true", help="Build and save CBMC command without executing CBMC")
    parser.add_argument("--force", action="store_true", help="Reserved for future use; currently records intent only")
    parser.add_argument("--timeout-seconds", type=int, default=None, help="Override CBMC timeout in seconds")
    return parser


def main(argv: Optional[List[str]] = None) -> int:
    args = build_arg_parser().parse_args(argv)
    agent = ToolExecutionAgent(
        config_path=Path(args.config),
        run_dir=Path(args.run_dir) if args.run_dir else None,
        iteration=args.iteration,
        artifact=args.artifact,
        dry_run=args.dry_run,
        force=args.force,
        timeout_seconds=args.timeout_seconds,
    )
    return agent.run()


if __name__ == "__main__":
    raise SystemExit(main())
